options(servr.daemon = TRUE)
options(blogdown.author = "Ilja / fubits")
options(blogdown.ext = ".Rmd")
options(blogdown.widgetsID = TRUE)
# options(blogdown.generator.server = TRUE)
options(blogdown.hugo.server = c("-D", "-F", "--navigateToChanged"))
