---
title: 'Test'
author: ''
date: '2018-11-29'
slug: index
# output:
#   blogdown::html_page:
#     number_sections: yes
#     toc: yes
output: html_document
params:
  output_file:"index.html"
categories:
  - R
  - Blogdown
tags:
  - GIS
  - Leaflet
---

```{r include=FALSE, eval=FALSE}
# render magic (manual rendering)
rmarkdown::render("index.Rmd")
```

```{r message=FALSE}
library(tidyverse)
library(sf)
```


```{r cache=TRUE}
dc_crime <- sf::st_read("https://opendata.arcgis.com/datasets/dc3289eab3d2400ea49c154863312434_8.geojson", quiet = TRUE)
```

```{r}
library(leaflet)
```

```{r out.width = '100%'}
leaflet() %>% 
  addTiles() %>% 
  addCircles(data = dc_crime, color = "#800000")
```


```{r}
# library(leaflet.extras)
```

```{r out.width = '100%'}
leaflet() %>% 
  addTiles() %>% 
  setView(13.37, 52.525, zoom = 17)
```

---

There are two ways. The quick & dirty way is to use the `x` package, which will give us the widget as an `iframe`:
```{r}
# install.packages('widgetframe')
library(widgetframe)
```

# Slides

```{r out.width = '100%', fig.asp=1.78}
knitr::include_url('rblogdown/rblogdown.html')
```

# DT::datatable()

```{r out.width = "100%", out.height = "100%"}
DT::datatable(
  head(iris, 10),
  fillContainer = FALSE, options = list(pageLength = 8)) %>% frameWidget()
```

the robust way: [StackOverflow](https://stackoverflow.com/questions/43594039/dt-package-not-working-with-blogdown-using-hugo-future-imperfect-theme){target="_blank"}

