---
title: '[R] German Academic Twitter, Pt. 2: From Data to Corpus with a Turkish Twist'
author: Ilja / fubits
date: '2018-10-07'
categories:
  - Rstats
  - Data Mining
  - Natural Language Processing NLP
tags:
  - Quanteda
  - Twitter
slug: r-german-academic-twitter-pt-2-from-data-to-corpus-with-a-turkish-twist
output:
  blogdown::html_page:
    number_sections: yes
    toc: yes
lastmod: '2018-10-07T21:58:18+02:00'
description: "Last week, I mined almost 5K Tweets from the annual meetings of five German academic societies. Now it's about time that we dive into the contents with Kenneth Benoit's powerful `quanteda` Package. Come for the corpus approaches to text as data, stay for the Turkish Plot-Twist..."
abstract: "We'll learn about constructing a document-feature matrix (dfm), applying exhaustive stopword-lists, the pitfalls of working with text as data, and most importantly acknowledge and learn from mistakes..."
thumbnail: "/img/thumbs/conference_tweets_pt2.jpg"
rmdlink: TRUE # Optional
keywords: []
comment: no
# toc: no
autoCollapseToc: no
postMetaInFooter: no
hiddenFromHomePage: no
contentCopyright: no
reward: no
mathjax: no
mathjaxEnableSingleDollar: no
mathjaxEnableAutoNumber: no
hideHeaderAndFooter: no
flowchartDiagrams:
  enable: no
  options: ''
sequenceDiagrams:
  enable: no
  options: ''
---


<div id="TOC">
<ul>
<li><a href="#import-tweets-from-.rds"><span class="toc-section-number">1</span> Import Tweets from <code>.rds</code></a><ul>
<li><a href="#subset-interdisciplinary-tweets"><span class="toc-section-number">1.1</span> Subset “Interdisciplinary” Tweets</a></li>
<li><a href="#inspect-interdisciplinary-tweets"><span class="toc-section-number">1.2</span> Inspect “Interdisciplinary” Tweets</a></li>
</ul></li>
<li><a href="#create-corpus"><span class="toc-section-number">2</span> Create Corpus</a><ul>
<li><a href="#build-individual-corpora"><span class="toc-section-number">2.1</span> Build Individual Corpora</a></li>
<li><a href="#create-joint-corpus"><span class="toc-section-number">2.2</span> Create Joint Corpus</a></li>
</ul></li>
<li><a href="#create-dfm"><span class="toc-section-number">3</span> Create DFM</a><ul>
<li><a href="#naive"><span class="toc-section-number">3.1</span> Naive</a></li>
<li><a href="#nd-attempt-remove-stopwordsgerman"><span class="toc-section-number">3.2</span> 2nd Attempt: Remove <code>stopwords(&quot;german&quot;)</code></a><ul>
<li><a href="#inspect-quantedas-built-in-stop-words"><span class="toc-section-number">3.2.1</span> Inspect <code>quanteda's</code> built-in Stop Words</a></li>
<li><a href="#include-custom-stopwords-and-remove-english-stopwords"><span class="toc-section-number">3.2.2</span> Include Custom Stopwords and Remove English Stopwords</a></li>
<li><a href="#inspect-keyword-in-context-kwic-for-amp"><span class="toc-section-number">3.2.3</span> Inspect “Keyword in Context” <code>kwic()</code> for “amp”</a></li>
<li><a href="#inspect-the-tokens-innen-and-bu-kwic."><span class="toc-section-number">3.2.4</span> Inspect the Tokens <code>&quot;innen&quot;</code> and <code>&quot;bu&quot;</code> <code>kwic()</code>.</a></li>
</ul></li>
</ul></li>
<li><a href="#the-turkish-plot-twist"><span class="toc-section-number">4</span> The Turkish Plot-Twist</a><ul>
<li><a href="#one-last-mystery-remains"><span class="toc-section-number">4.1</span> One last Mystery remains…</a></li>
<li><a href="#removing-turkish-accounts"><span class="toc-section-number">4.2</span> Removing Turkish accounts</a></li>
</ul></li>
<li><a href="#rebuild-the-corpus-without-tweets-with-langtr"><span class="toc-section-number">5</span> Rebuild the Corpus without Tweets with <code>lang==&quot;tr&quot;</code></a><ul>
<li><a href="#re-build-individual-corpora-from-scratch"><span class="toc-section-number">5.1</span> Re-Build individual Corpora from Scratch</a></li>
<li><a href="#create-joint-corpus-1"><span class="toc-section-number">5.2</span> Create Joint Corpus</a></li>
</ul></li>
<li><a href="#rd-attempt-dfm-building"><span class="toc-section-number">6</span> 3rd Attempt @ <code>dfm()</code> Building</a></li>
<li><a href="#some-quick-analyses"><span class="toc-section-number">7</span> Some quick Analyses</a><ul>
<li><a href="#top-features-per-discipline"><span class="toc-section-number">7.1</span> Top Features per Discipline</a></li>
<li><a href="#hashtags"><span class="toc-section-number">7.2</span> Hashtags</a></li>
<li><a href="#network-of-feature-co-occurrences"><span class="toc-section-number">7.3</span> Network of feature co-occurrences</a></li>
<li><a href="#grouped-wordcloud-of-features"><span class="toc-section-number">7.4</span> Grouped wordcloud of features</a></li>
</ul></li>
<li><a href="#whats-next"><span class="toc-section-number">8</span> What’s next?</a></li>
</ul>
</div>

<p>Last week, I <a href="https://ellocke.github.io/post/r-academic-conference-twitter-pt-1-mining-dvpw18-dgs18-hist18-et-al/">mined almost 5K Tweets</a> from the annual meetings of five German academic societies. Now it’s about time that we dive into the contents with <a href="https://twitter.com/kenbenoit" target="_blank">Kenneth Benoit’s</a> powerful <code>quanteda</code> Package. Come for the corpus approaches to text as data, stay for the Turkish Plot-Twist…</p>
<pre class="r"><code>library(tidyverse)
library(here)
library(rtweet) # just in case we want to look up something on Twitter
library(quanteda)
quanteda_options(&quot;threads&quot; = 4)
# quanteda_options(&quot;threads&quot;)</code></pre>
<div id="import-tweets-from-.rds" class="section level1">
<h1><span class="header-section-number">1</span> Import Tweets from <code>.rds</code></h1>
<p>Please see <a href="https://ellocke.github.io/post/r-academic-conference-twitter-pt-1-mining-dvpw18-dgs18-hist18-et-al/">Twitter pt. 1</a> for Twitter Mining with <code>rtweet</code> and the details of the data handling approach.</p>
<p><strong>Prepare here()-path to the <code>.rds</code> data</strong></p>
<pre class="r"><code>data_path &lt;- here(&quot;static&quot;, &quot;data&quot;, &quot;ConferenceTweets&quot;, &quot;/&quot;)</code></pre>
<p><strong>Bulk-read the <code>.rds</code> files</strong></p>
<pre class="r"><code>dvpw_collection &lt;- dir(path = data_path, pattern = &quot;dvpw_&quot;) %&gt;% 
  str_c(data_path, .) %&gt;% 
  map_dfr(readRDS)
dvpw_collection &lt;- dvpw_collection %&gt;% distinct(status_id, .keep_all = TRUE) %&gt;%
  filter(created_at &lt; &quot;2018-09-30&quot;) %&gt;%
  mutate(Discipline = &quot;PolSci&quot;) %&gt;% 
  arrange(created_at)

dgs_collection &lt;- dir(path = data_path, pattern = &quot;dgs_&quot;) %&gt;% 
  str_c(data_path, .) %&gt;% 
  map_dfr(readRDS)
dgs_collection &lt;- dgs_collection %&gt;% distinct(status_id, .keep_all = TRUE) %&gt;%
  filter(created_at &lt; &quot;2018-09-30&quot;) %&gt;%
  mutate(Discipline = &quot;Sociology&quot;) %&gt;% 
  arrange(created_at)

hist_collection &lt;- dir(path = data_path, pattern = &quot;hist_&quot;) %&gt;% 
  str_c(data_path, .) %&gt;% 
  map_dfr(readRDS)
hist_collection &lt;- hist_collection %&gt;% distinct(status_id, .keep_all = TRUE) %&gt;%
  filter(created_at &lt; &quot;2018-09-30&quot;) %&gt;%
  mutate(Discipline = &quot;History&quot;) %&gt;% 
  arrange(created_at)

inf_collection &lt;- dir(path = data_path, pattern = &quot;inf_&quot;) %&gt;% 
  str_c(data_path, .) %&gt;% 
  map_dfr(readRDS)
inf_collection &lt;- inf_collection %&gt;% distinct(status_id, .keep_all = TRUE) %&gt;%
  filter(created_at &lt; &quot;2018-09-30&quot;) %&gt;%
  mutate(Discipline = &quot;CS&quot;) %&gt;% 
  arrange(created_at)</code></pre>
<div id="subset-interdisciplinary-tweets" class="section level2">
<h2><span class="header-section-number">1.1</span> Subset “Interdisciplinary” Tweets</h2>
<p>Something I didn’t account for last time, was the possibility that some Twitter Users might have been mentioning / monitoring multiple conferences, esp. with regards to the interrelation between Political Science, Sociology, and History.</p>
<p>Let’s single them out and assign a “Mixed” label.</p>
<pre class="r"><code>joint_collection &lt;- bind_rows(dvpw_collection, dgs_collection,
                              hist_collection, inf_collection)

# build set of distinct 
joint_distinct &lt;- joint_collection %&gt;% 
  distinct(status_id, .keep_all = TRUE)

#subset duplicated
mixed_collection &lt;- subset(joint_collection,
                      duplicated(joint_collection$status_id)) %&gt;% 
  distinct(status_id, .keep_all = TRUE) # find duplicates

mixed_collection$Discipline &lt;- &quot;Mixed&quot;</code></pre>
<blockquote>
<p>Only 42 Tweets? Out of a sample of almost 5K? Twitter Silos, anyone?</p>
</blockquote>
</div>
<div id="inspect-interdisciplinary-tweets" class="section level2">
<h2><span class="header-section-number">1.2</span> Inspect “Interdisciplinary” Tweets</h2>
<pre class="r"><code>mixed_collection %&gt;% 
  arrange(created_at) %&gt;% 
  select(text) %&gt;% head(10) %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
text
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Gut, dass das Team des <span class="citation">@fgf_nrw</span> etwas größer ist: Wir sind diese Woche vertreten: #dgs18, #dvpw18 und ab Mittwoch bei der KEG in Wien <a href="https://t.co/jiE6SyfKHe" class="uri">https://t.co/jiE6SyfKHe</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
Hier noch eine wichtige Ansage: #dvpw18 muss unbedingt vor #dgs18 trenden
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@daniellambach</span> Das wollen die von den Naturwissenschaften doch nur, dass wir Sozial- und Geisteswissenschaftler*innen uns gegenseitig bekriegen. 😉 #dvpw18 #histag18 #dgs18
</td>
</tr>
<tr>
<td style="text-align:left;">
Leider findet die #dvpw18 gleichzeitig mit dem #dgs2018 statt. Wäre sehr gern auch bei Euch, <span class="citation">@mlewandowsky</span>, <span class="citation">@wahlforschung</span> und <span class="citation">@thothiel</span> :/
</td>
</tr>
<tr>
<td style="text-align:left;">
Paar Minuten im 1. Vortrag #infdh2018 reichen schon, um mal ganz deutlich zu sehen um wie viele Größenordnungen die digitalen Geisteswissenschaften den “digitalen” Sozialwissenschaften handwerklich und institutionell voraus sind. Grüße an #dvpw18 und #dgs18 <a href="https://t.co/TZU8E9PecT" class="uri">https://t.co/TZU8E9PecT</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
Meine Wunsch an #ScienceTwitter jetzt wo #dvpw18 &amp;amp; #HisTag18 &amp;amp; #dgs18 parallel laufen: Kann jemand analysieren, wie viel Schnittmenge es zwischen den Programmen gibt?
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@DrMichaelHein</span> <span class="citation">@dvpwkongress</span> #dgs18 #dvpw18 #histag18 ich fände es ja schöner auf spannende Themen gemeinsam zu blicken, die wir gesellschaftlich gemeinsam diskutieren könnten/sollten, und nicht Trennungslinien und Wettbewerb aufzumachen…
</td>
</tr>
<tr>
<td style="text-align:left;">
Kleine Pause gefällig? Unter den Hashtags #ddss18, #dgs18 und #HisTag18 kann man sehr interessanten Veranstaltungen aus der Ferne beiwohnen. #gswtud <a href="https://t.co/VlfzaYpjrb" class="uri">https://t.co/VlfzaYpjrb</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
Wie wäre es mit einem gemeinsamen Soziohistostaatsrechtspolitolog*innentag 2021? <span class="citation">@dvpwkongress</span> <span class="citation">@dvpw</span> <span class="citation">@DGSoziologie</span> <span class="citation">@historikertag</span> <span class="citation">@vdstrl</span> #dvpw18 #histag18 #dgs18 #vdstrl18 <a href="https://t.co/EgZYmaikqY" class="uri">https://t.co/EgZYmaikqY</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
während die lieben kolleg(inn)en bei #dvpw18, #dgs18 &amp;amp; #HisTag18 um die besten tweets auf #twitter ringen, schauen wir von #GSA2018 aus pittsburgh zu. good luck, friends! 😇
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="create-corpus" class="section level1">
<h1><span class="header-section-number">2</span> Create Corpus</h1>
<p>For further, “Corpus-based”&quot; analysis (and beyond) we’ll use the <code>quanteda</code> package.</p>
<p>I aim to re-do as much as I can from this series with <a href="https://twitter.com/juliasilge" target="_blank">Julia Silge’s</a> <code>tidytext</code> package, soon, btw.</p>
<div id="build-individual-corpora" class="section level2">
<h2><span class="header-section-number">2.1</span> Build Individual Corpora</h2>
<p>As we already have singled out “interdisciplinary” Tweets, we’ll just <code>anti_join()</code> every other tibble with the mixed Tweets.</p>
<pre class="r"><code>dvpw_corpus &lt;- dvpw_collection %&gt;%
  anti_join(mixed_collection, by = &quot;status_id&quot;) %&gt;% 
  corpus(docid_field = &quot;status_id&quot;)
docvars(dvpw_corpus, &quot;Discipline&quot;) &lt;- &quot;PolSci&quot;

dgs_corpus &lt;- dgs_collection %&gt;% 
  anti_join(mixed_collection, by = &quot;status_id&quot;) %&gt;% 
  corpus(docid_field = &quot;status_id&quot;)
docvars(dgs_corpus, &quot;Discipline&quot;) &lt;- &quot;Sociology&quot;

hist_corpus &lt;- hist_collection %&gt;% 
  anti_join(mixed_collection, by = &quot;status_id&quot;) %&gt;% 
  corpus(docid_field = &quot;status_id&quot;)
docvars(hist_corpus, &quot;Discipline&quot;) &lt;- &quot;History&quot;

inf_corpus &lt;- inf_collection %&gt;% 
  anti_join(mixed_collection, by = &quot;status_id&quot;) %&gt;% 
  corpus(docid_field = &quot;status_id&quot;)
docvars(inf_corpus, &quot;Discipline&quot;) &lt;- &quot;CS&quot;

mixed_corpus &lt;- mixed_collection  %&gt;% 
  corpus(docid_field = &quot;status_id&quot;)
docvars(mixed_corpus, &quot;Discipline&quot;) &lt;- &quot;Mixed&quot;</code></pre>
</div>
<div id="create-joint-corpus" class="section level2">
<h2><span class="header-section-number">2.2</span> Create Joint Corpus</h2>
<p>That’s even easier thanks to Quanteda.</p>
<pre class="r"><code>joint_corpus &lt;- dvpw_corpus + 
                dgs_corpus + 
                hist_corpus + 
                inf_corpus + 
                mixed_corpus</code></pre>
</div>
</div>
<div id="create-dfm" class="section level1">
<h1><span class="header-section-number">3</span> Create DFM</h1>
<p>For most really usuful approaches to “text as data” we’ll need a sparse document-feature matrix (dfm). Doing this with quanteda is straight forward, but there are some less prominent Tweets.</p>
<div id="naive" class="section level2">
<h2><span class="header-section-number">3.1</span> Naive</h2>
<pre class="r"><code>joint_dfm &lt;- dfm(joint_corpus,
                # groups = &quot;Discipline&quot;,
                 remove_punct = TRUE, 
                 remove_url = TRUE, # it&#39;s a mess, without
                 tolower = TRUE,
                 verbose = FALSE) #for website readability</code></pre>
<pre class="r"><code>topfeatures(joint_dfm, 20) %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
x
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
der
</td>
<td style="text-align:right;">
2001
</td>
</tr>
<tr>
<td style="text-align:left;">
#dvpw18
</td>
<td style="text-align:right;">
1681
</td>
</tr>
<tr>
<td style="text-align:left;">
und
</td>
<td style="text-align:right;">
1661
</td>
</tr>
<tr>
<td style="text-align:left;">
die
</td>
<td style="text-align:right;">
1517
</td>
</tr>
<tr>
<td style="text-align:left;">
in
</td>
<td style="text-align:right;">
1214
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs2018
</td>
<td style="text-align:right;">
1174
</td>
</tr>
<tr>
<td style="text-align:left;">
#histag18
</td>
<td style="text-align:right;">
1037
</td>
</tr>
<tr>
<td style="text-align:left;">
auf
</td>
<td style="text-align:right;">
765
</td>
</tr>
<tr>
<td style="text-align:left;">
von
</td>
<td style="text-align:right;">
675
</td>
</tr>
<tr>
<td style="text-align:left;">
für
</td>
<td style="text-align:right;">
624
</td>
</tr>
<tr>
<td style="text-align:left;">
zu
</td>
<td style="text-align:right;">
601
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs18
</td>
<td style="text-align:right;">
584
</td>
</tr>
<tr>
<td style="text-align:left;">
das
</td>
<td style="text-align:right;">
583
</td>
</tr>
<tr>
<td style="text-align:left;">
mit
</td>
<td style="text-align:right;">
566
</td>
</tr>
<tr>
<td style="text-align:left;">
ist
</td>
<td style="text-align:right;">
520
</td>
</tr>
<tr>
<td style="text-align:left;">
the
</td>
<td style="text-align:right;">
515
</td>
</tr>
<tr>
<td style="text-align:left;">
den
</td>
<td style="text-align:right;">
480
</td>
</tr>
<tr>
<td style="text-align:left;">
des
</td>
<td style="text-align:right;">
452
</td>
</tr>
<tr>
<td style="text-align:left;">
im
</td>
<td style="text-align:right;">
437
</td>
</tr>
<tr>
<td style="text-align:left;">
dem
</td>
<td style="text-align:right;">
432
</td>
</tr>
</tbody>
</table>
<p>We get <code>nfeat(joint_dfm)</code> = 20832 features, but as we can see from the <code>topfeatures()</code> output, the top features are mostly (and unsurprisingly very common German words which are also know as <code>stopwords</code> in NLP).</p>
</div>
<div id="nd-attempt-remove-stopwordsgerman" class="section level2">
<h2><span class="header-section-number">3.2</span> 2nd Attempt: Remove <code>stopwords(&quot;german&quot;)</code></h2>
<pre class="r"><code>joint_dfm &lt;- dfm(joint_corpus,
                 # groups = &quot;Discipline&quot;,
                 remove = stopwords(&quot;german&quot;),
                 remove_punct = TRUE,
                 remove_url = TRUE,
                 tolower = TRUE,
                 verbose = FALSE) #for website readability
topfeatures(joint_dfm, 20) %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
x
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
#dvpw18
</td>
<td style="text-align:right;">
1681
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs2018
</td>
<td style="text-align:right;">
1174
</td>
</tr>
<tr>
<td style="text-align:left;">
#histag18
</td>
<td style="text-align:right;">
1037
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs18
</td>
<td style="text-align:right;">
584
</td>
</tr>
<tr>
<td style="text-align:left;">
the
</td>
<td style="text-align:right;">
515
</td>
</tr>
<tr>
<td style="text-align:left;">
of
</td>
<td style="text-align:right;">
357
</td>
</tr>
<tr>
<td style="text-align:left;">
and
</td>
<td style="text-align:right;">
337
</td>
</tr>
<tr>
<td style="text-align:left;">
#informatik2018
</td>
<td style="text-align:right;">
321
</td>
</tr>
<tr>
<td style="text-align:left;">
to
</td>
<td style="text-align:right;">
314
</td>
</tr>
<tr>
<td style="text-align:left;">
amp
</td>
<td style="text-align:right;">
224
</td>
</tr>
<tr>
<td style="text-align:left;">
a
</td>
<td style="text-align:right;">
223
</td>
</tr>
<tr>
<td style="text-align:left;">
heute
</td>
<td style="text-align:right;">
200
</td>
</tr>
<tr>
<td style="text-align:left;">
beim
</td>
<td style="text-align:right;">
184
</td>
</tr>
<tr>
<td style="text-align:left;">
on
</td>
<td style="text-align:right;">
175
</td>
</tr>
<tr>
<td style="text-align:left;">
panel
</td>
<td style="text-align:right;">
172
</td>
</tr>
<tr>
<td style="text-align:left;">
dass
</td>
<td style="text-align:right;">
168
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@dvpwkongress</span>
</td>
<td style="text-align:right;">
166
</td>
</tr>
<tr>
<td style="text-align:left;">
for
</td>
<td style="text-align:right;">
162
</td>
</tr>
<tr>
<td style="text-align:left;">
is
</td>
<td style="text-align:right;">
150
</td>
</tr>
<tr>
<td style="text-align:left;">
demokratie
</td>
<td style="text-align:right;">
145
</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Apart from English tokens (to, on, is, for, of, a), common German words such as “beim” or “dass” are still included. The latter is rather weird…</p>
</blockquote>
<div id="inspect-quantedas-built-in-stop-words" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Inspect <code>quanteda's</code> built-in Stop Words</h3>
<p>Since we’ve seen that “dass” is still included in our corpus, let’s i.e. look at all <code>quanteda::stopwords(&quot;german&quot;)</code> starting with a “d”:</p>
<pre class="r"><code>stopwords(&quot;german&quot;) %&gt;%
  as_tibble() %&gt;%
  filter(str_detect(value, pattern = &quot;^da.*&quot;)) %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
da
</td>
</tr>
<tr>
<td style="text-align:left;">
damit
</td>
</tr>
<tr>
<td style="text-align:left;">
dann
</td>
</tr>
<tr>
<td style="text-align:left;">
das
</td>
</tr>
<tr>
<td style="text-align:left;">
daß
</td>
</tr>
<tr>
<td style="text-align:left;">
dasselbe
</td>
</tr>
<tr>
<td style="text-align:left;">
dazu
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># missing: beim</code></pre>
<blockquote>
<p>Ok, “daß” instead of “dass” suggests that <code>quanteda</code>’s stopword list for German terms might need an update… :)</p>
</blockquote>
<p>Also, note how <code>stopwords(&quot;german&quot;)</code> consists of 231 tokens. Just for comparison, <code>tidytext::stop_words</code> has a total of 1149 stopwords for English. So we probably will have to include custom stopword lists repeatedly.</p>
<blockquote>
<p>Of course, GitHub has you covered! Gene Diaz is maintaining a super-exhaustive list of stopwords for multiple languages: <a href="https://github.com/stopwords-iso" target="_blank">github.com/stopwords-iso</a></p>
</blockquote>
<blockquote>
<p>We’ll use the text file with the German stopwords: <a href="https://raw.githubusercontent.com/stopwords-iso/stopwords-de/master/stopwords-de.txt" target="_blank">stopwords-de.txt</a></p>
</blockquote>
<pre class="r"><code>ger_stopwords &lt;- read_lines(&quot;https://raw.githubusercontent.com/stopwords-iso/stopwords-de/master/stopwords-de.txt&quot;)
# saveRDS(ger_stopwords, &quot;ger_stopwords.rds&quot;)
length(ger_stopwords) #&gt; 621 stopwords</code></pre>
<pre><code>## [1] 621</code></pre>
<pre class="r"><code>c(ger_stopwords, stopwords(&quot;german&quot;)) %&gt;% length() #&gt; 852</code></pre>
<pre><code>## [1] 852</code></pre>
<pre class="r"><code>c(ger_stopwords, stopwords(&quot;german&quot;)) %&gt;% unique() %&gt;% length() #&gt; 621</code></pre>
<pre><code>## [1] 621</code></pre>
</div>
<div id="include-custom-stopwords-and-remove-english-stopwords" class="section level3">
<h3><span class="header-section-number">3.2.2</span> Include Custom Stopwords and Remove English Stopwords</h3>
<pre class="r"><code>c(&quot;dass&quot;, &quot;beim&quot;) %in% ger_stopwords #&gt; [1] TRUE TRUE</code></pre>
<pre><code>## [1] TRUE TRUE</code></pre>
<pre class="r"><code># custom_stopwords &lt;- c(&quot;dass&quot;, &quot;beim&quot;)
custom_stopwords &lt;- setdiff(ger_stopwords, stopwords(&quot;german&quot;)) # only keep left set</code></pre>
<pre class="r"><code>joint_dfm &lt;- dfm(joint_corpus,
                 # groups = &quot;Discipline&quot;,
                 remove = c(stopwords(&quot;german&quot;),
                            stopwords(&quot;english&quot;), # ONE
                            custom_stopwords, # TWO
                            min_nchar = 2), # THREE
                 remove_punct = TRUE,
                 remove_url = TRUE,
                 tolower = TRUE,
                 verbose = FALSE) #for website readability
topfeatures(joint_dfm, 20) %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
x
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
#dvpw18
</td>
<td style="text-align:right;">
1681
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs2018
</td>
<td style="text-align:right;">
1174
</td>
</tr>
<tr>
<td style="text-align:left;">
#histag18
</td>
<td style="text-align:right;">
1037
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs18
</td>
<td style="text-align:right;">
584
</td>
</tr>
<tr>
<td style="text-align:left;">
#informatik2018
</td>
<td style="text-align:right;">
321
</td>
</tr>
<tr>
<td style="text-align:left;">
amp
</td>
<td style="text-align:right;">
224
</td>
</tr>
<tr>
<td style="text-align:left;">
panel
</td>
<td style="text-align:right;">
172
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@dvpwkongress</span>
</td>
<td style="text-align:right;">
166
</td>
</tr>
<tr>
<td style="text-align:left;">
demokratie
</td>
<td style="text-align:right;">
145
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@osymbaskanligi</span>
</td>
<td style="text-align:right;">
123
</td>
</tr>
<tr>
<td style="text-align:left;">
dgs
</td>
<td style="text-align:right;">
121
</td>
</tr>
<tr>
<td style="text-align:left;">
innen
</td>
<td style="text-align:right;">
114
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs
</td>
<td style="text-align:right;">
113
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@dvpw</span>
</td>
<td style="text-align:right;">
112
</td>
</tr>
<tr>
<td style="text-align:left;">
#dvpw2018
</td>
<td style="text-align:right;">
111
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@historikertag</span>
</td>
<td style="text-align:right;">
109
</td>
</tr>
<tr>
<td style="text-align:left;">
bu
</td>
<td style="text-align:right;">
106
</td>
</tr>
<tr>
<td style="text-align:left;">
de
</td>
<td style="text-align:right;">
97
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@dgsoziologie</span>
</td>
<td style="text-align:right;">
95
</td>
</tr>
<tr>
<td style="text-align:left;">
mı
</td>
<td style="text-align:right;">
94
</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Great. But … what is “amp”???</p>
</blockquote>
</div>
<div id="inspect-keyword-in-context-kwic-for-amp" class="section level3">
<h3><span class="header-section-number">3.2.3</span> Inspect “Keyword in Context” <code>kwic()</code> for “amp”</h3>
<pre class="r"><code>kwic(joint_corpus, &quot;amp&quot;, window = 3)  %&gt;%
  # vs. kwic(x, phrase(&quot;term1 term2&quot;))
  as_tibble() %&gt;% # needed for kwic()
  select(pre:post) %&gt;%
  head(10) %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
pre
</th>
<th style="text-align:left;">
keyword
</th>
<th style="text-align:left;">
post
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<span class="citation">@ifp_tuebingen</span> ) &amp;
</td>
<td style="text-align:left;">
amp
</td>
<td style="text-align:left;">
; I organise
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@goetheuni</span> ) &amp;
</td>
<td style="text-align:left;">
amp
</td>
<td style="text-align:left;">
; Jonas Wolff
</td>
</tr>
<tr>
<td style="text-align:left;">
pu­blic goods &amp;
</td>
<td style="text-align:left;">
amp
</td>
<td style="text-align:left;">
; to pre­vent
</td>
</tr>
<tr>
<td style="text-align:left;">
die Vorträge &amp;
</td>
<td style="text-align:left;">
amp
</td>
<td style="text-align:left;">
; Panelleitungen von
</td>
</tr>
<tr>
<td style="text-align:left;">
von #InIIS &amp;
</td>
<td style="text-align:left;">
amp
</td>
<td style="text-align:left;">
; <span class="citation">@BIGSSS_Bremen</span> Kolleg
</td>
</tr>
<tr>
<td style="text-align:left;">
Viel Erfolg &amp;
</td>
<td style="text-align:left;">
amp
</td>
<td style="text-align:left;">
; Spaß den
</td>
</tr>
<tr>
<td style="text-align:left;">
&quot; #PolComm &amp;
</td>
<td style="text-align:left;">
amp
</td>
<td style="text-align:left;">
; Digital Complexity
</td>
</tr>
<tr>
<td style="text-align:left;">
, <span class="citation">@SFB1342</span> &amp;
</td>
<td style="text-align:left;">
amp
</td>
<td style="text-align:left;">
; von überall
</td>
</tr>
<tr>
<td style="text-align:left;">
bestimmt spannende &amp;
</td>
<td style="text-align:left;">
amp
</td>
<td style="text-align:left;">
; inspirierende Tage
</td>
</tr>
<tr>
<td style="text-align:left;">
nach #Adorno &amp;
</td>
<td style="text-align:left;">
amp
</td>
<td style="text-align:left;">
; Co gehen
</td>
</tr>
</tbody>
</table>
<blockquote>
<p>“amp” == “&amp;amp” which is the <code>HTML</code> term for &amp; / ampersand (but “&amp;” is removed when we create the corpus with <code>remove_punct = TRUE</code>, so only “amp” remains. Cool.)</p>
</blockquote>
<p>Remove “amp”</p>
<pre class="r"><code>custom_stopwords &lt;- c(custom_stopwords, &quot;amp&quot;)
# This way, we&#39;ll keep our custom &quot;amp&quot; and &quot;innen&quot;
joint_dfm &lt;- dfm(joint_corpus,
                 # groups = &quot;Discipline&quot;,
                 remove = c(stopwords(&quot;german&quot;),
                            stopwords(&quot;english&quot;),
                            custom_stopwords,
                            min_nchar = 2),
                 remove_punct = TRUE,
                 remove_url = TRUE,
                 tolower = TRUE,
                 verbose = FALSE) #for website readability
topfeatures(joint_dfm, 20) %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
x
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
#dvpw18
</td>
<td style="text-align:right;">
1681
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs2018
</td>
<td style="text-align:right;">
1174
</td>
</tr>
<tr>
<td style="text-align:left;">
#histag18
</td>
<td style="text-align:right;">
1037
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs18
</td>
<td style="text-align:right;">
584
</td>
</tr>
<tr>
<td style="text-align:left;">
#informatik2018
</td>
<td style="text-align:right;">
321
</td>
</tr>
<tr>
<td style="text-align:left;">
panel
</td>
<td style="text-align:right;">
172
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@dvpwkongress</span>
</td>
<td style="text-align:right;">
166
</td>
</tr>
<tr>
<td style="text-align:left;">
demokratie
</td>
<td style="text-align:right;">
145
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@osymbaskanligi</span>
</td>
<td style="text-align:right;">
123
</td>
</tr>
<tr>
<td style="text-align:left;">
dgs
</td>
<td style="text-align:right;">
121
</td>
</tr>
<tr>
<td style="text-align:left;">
innen
</td>
<td style="text-align:right;">
114
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs
</td>
<td style="text-align:right;">
113
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@dvpw</span>
</td>
<td style="text-align:right;">
112
</td>
</tr>
<tr>
<td style="text-align:left;">
#dvpw2018
</td>
<td style="text-align:right;">
111
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@historikertag</span>
</td>
<td style="text-align:right;">
109
</td>
</tr>
<tr>
<td style="text-align:left;">
bu
</td>
<td style="text-align:right;">
106
</td>
</tr>
<tr>
<td style="text-align:left;">
de
</td>
<td style="text-align:right;">
97
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@dgsoziologie</span>
</td>
<td style="text-align:right;">
95
</td>
</tr>
<tr>
<td style="text-align:left;">
mı
</td>
<td style="text-align:right;">
94
</td>
</tr>
<tr>
<td style="text-align:left;">
thema
</td>
<td style="text-align:right;">
93
</td>
</tr>
</tbody>
</table>
<blockquote>
<p>That’s better. But what’s up with “innen” and “bu”?</p>
</blockquote>
</div>
<div id="inspect-the-tokens-innen-and-bu-kwic." class="section level3">
<h3><span class="header-section-number">3.2.4</span> Inspect the Tokens <code>&quot;innen&quot;</code> and <code>&quot;bu&quot;</code> <code>kwic()</code>.</h3>
<pre class="r"><code>kwic(joint_corpus, &quot;innen&quot;, window = 3)  %&gt;% 
  as_tibble() %&gt;% # needed for kwic()
  select(pre:post) %&gt;%
  head(10) %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
pre
</th>
<th style="text-align:left;">
keyword
</th>
<th style="text-align:left;">
post
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<span class="citation">@BIGSSS_Bremen</span> Kolleg *
</td>
<td style="text-align:left;">
innen
</td>
<td style="text-align:left;">
. Da ist
</td>
</tr>
<tr>
<td style="text-align:left;">
| ler *
</td>
<td style="text-align:left;">
innen
</td>
<td style="text-align:left;">
vor Ort #powi
</td>
</tr>
<tr>
<td style="text-align:left;">
#powi Kolleg *
</td>
<td style="text-align:left;">
innen
</td>
<td style="text-align:left;">
von <span class="citation">@UniBremen</span> ,
</td>
</tr>
<tr>
<td style="text-align:left;">
. Kolleg /
</td>
<td style="text-align:left;">
innen
</td>
<td style="text-align:left;">
der <span class="citation">@unihh</span> im
</td>
</tr>
<tr>
<td style="text-align:left;">
Kolleg /
</td>
<td style="text-align:left;">
innen
</td>
<td style="text-align:left;">
vom Institut für
</td>
</tr>
<tr>
<td style="text-align:left;">
die Kolleg /
</td>
<td style="text-align:left;">
innen
</td>
<td style="text-align:left;">
mit dem Peer
</td>
</tr>
<tr>
<td style="text-align:left;">
1000 Expert *
</td>
<td style="text-align:left;">
innen
</td>
<td style="text-align:left;">
sucht , die
</td>
</tr>
<tr>
<td style="text-align:left;">
loyale Bürger /
</td>
<td style="text-align:left;">
innen
</td>
<td style="text-align:left;">
oder auch bürgerliche
</td>
</tr>
<tr>
<td style="text-align:left;">
mit Rassist *
</td>
<td style="text-align:left;">
innen
</td>
<td style="text-align:left;">
, Antisemit *
</td>
</tr>
<tr>
<td style="text-align:left;">
, Antisemit *
</td>
<td style="text-align:left;">
innen
</td>
<td style="text-align:left;">
, und Nazis
</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Ok, so <code>&quot;&lt; / | * &gt;innen&quot;</code> is part of the gendered forms of plurals of German terms such as Colleagues, Citizens, Rassists et al. We might want to think of a robust solution - which should not be stemming - here. Maybe <code>ngrams=2</code> or some clever <code>str_c(&lt;regex&gt; + (* | /) + &quot;innen&quot;&quot;)</code> might help. But for now we’ll just add <code>&quot;innen&quot;</code> as a stopword.</p>
</blockquote>
<pre class="r"><code>custom_stopwords &lt;- c(custom_stopwords, &quot;innen&quot;)
joint_dfm &lt;- dfm(joint_corpus,
                 # groups = &quot;Discipline&quot;,
                 remove = c(stopwords(&quot;german&quot;),
                            stopwords(&quot;english&quot;),
                            custom_stopwords,
                            min_nchar = 2),
                 remove_punct = TRUE,
                 remove_url = TRUE,
                 tolower = TRUE,
                 verbose = FALSE) #for website readability
topfeatures(joint_dfm, 20) %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
x
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
#dvpw18
</td>
<td style="text-align:right;">
1681
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs2018
</td>
<td style="text-align:right;">
1174
</td>
</tr>
<tr>
<td style="text-align:left;">
#histag18
</td>
<td style="text-align:right;">
1037
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs18
</td>
<td style="text-align:right;">
584
</td>
</tr>
<tr>
<td style="text-align:left;">
#informatik2018
</td>
<td style="text-align:right;">
321
</td>
</tr>
<tr>
<td style="text-align:left;">
panel
</td>
<td style="text-align:right;">
172
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@dvpwkongress</span>
</td>
<td style="text-align:right;">
166
</td>
</tr>
<tr>
<td style="text-align:left;">
demokratie
</td>
<td style="text-align:right;">
145
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@osymbaskanligi</span>
</td>
<td style="text-align:right;">
123
</td>
</tr>
<tr>
<td style="text-align:left;">
dgs
</td>
<td style="text-align:right;">
121
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs
</td>
<td style="text-align:right;">
113
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@dvpw</span>
</td>
<td style="text-align:right;">
112
</td>
</tr>
<tr>
<td style="text-align:left;">
#dvpw2018
</td>
<td style="text-align:right;">
111
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@historikertag</span>
</td>
<td style="text-align:right;">
109
</td>
</tr>
<tr>
<td style="text-align:left;">
bu
</td>
<td style="text-align:right;">
106
</td>
</tr>
<tr>
<td style="text-align:left;">
de
</td>
<td style="text-align:right;">
97
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@dgsoziologie</span>
</td>
<td style="text-align:right;">
95
</td>
</tr>
<tr>
<td style="text-align:left;">
mı
</td>
<td style="text-align:right;">
94
</td>
</tr>
<tr>
<td style="text-align:left;">
thema
</td>
<td style="text-align:right;">
93
</td>
</tr>
<tr>
<td style="text-align:left;">
bir
</td>
<td style="text-align:right;">
89
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="the-turkish-plot-twist" class="section level1">
<h1><span class="header-section-number">4</span> The Turkish Plot-Twist</h1>
<div id="one-last-mystery-remains" class="section level2">
<h2><span class="header-section-number">4.1</span> One last Mystery remains…</h2>
<p>So what about <code>&quot;bu&quot;</code>?</p>
<blockquote>
<p>(Spoiler: <a href="https://twitter.com/OSYMbaskanligi" target="_blank"><code>@osymbaskanligi</code></a> seems to be an offical governmental Turkish account… That already points at something bigger.)</p>
</blockquote>
<pre class="r"><code>kwic(joint_corpus, &quot;bu&quot;, window = 3) %&gt;% 
  as_tibble() %&gt;% # needed for kwic()
  select(pre:post) %&gt;%
  head(10) %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
pre
</th>
<th style="text-align:left;">
keyword
</th>
<th style="text-align:left;">
post
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
#dgs2018 keşke
</td>
<td style="text-align:left;">
bu
</td>
<td style="text-align:left;">
gece açıklansa 🙄
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs2018
</td>
<td style="text-align:left;">
bu
</td>
<td style="text-align:left;">
gecenin en büyük
</td>
</tr>
<tr>
<td style="text-align:left;">
otomatik olarak yapıyorsa
</td>
<td style="text-align:left;">
bu
</td>
<td style="text-align:left;">
bekleyiş neden ?
</td>
</tr>
<tr>
<td style="text-align:left;">
sonuçlarını açıklamak neden
</td>
<td style="text-align:left;">
bu
</td>
<td style="text-align:left;">
kadar uzun sürüyor
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
Bu
</td>
<td style="text-align:left;">
yaşta bu kadar
</td>
</tr>
<tr>
<td style="text-align:left;">
Bu yaşta
</td>
<td style="text-align:left;">
bu
</td>
<td style="text-align:left;">
kadar sıkıntı yeter
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@OSYMbaskanligi</span> ceza mı
</td>
<td style="text-align:left;">
bu
</td>
<td style="text-align:left;">
ne şimdi #dgs2018
</td>
</tr>
<tr>
<td style="text-align:left;">
, DGS neden
</td>
<td style="text-align:left;">
bu
</td>
<td style="text-align:left;">
kadar itibarsızlaştırılıyor ?
</td>
</tr>
<tr>
<td style="text-align:left;">
halde bekliyorum ve
</td>
<td style="text-align:left;">
bu
</td>
<td style="text-align:left;">
beni rahatsiz ediyo
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
Bu
</td>
<td style="text-align:left;">
#dgs2018 yüzünden internette
</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Turkish? Huh? Seems like the Sociologists’ hashtag (#dgs18, #dgs2018) was heaviliy used by the Turkish Twitter community, too.</p>
</blockquote>
<pre class="r"><code>dgs_collection %&gt;% filter(lang == &quot;tr&quot;) %&gt;% count()</code></pre>
<pre><code>## # A tibble: 1 x 1
##       n
##   &lt;int&gt;
## 1   957</code></pre>
<blockquote>
<p>Oopsie… From the Sociology Corpus, 957 Tweets out of 1674 are labelled as Turkish…</p>
</blockquote>
<blockquote>
<p>WHAT ELSE DID I MISS?</p>
</blockquote>
<pre class="r"><code>dgs_collection %&gt;% group_by(lang) %&gt;% count() %&gt;% arrange(desc(n)) %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
lang
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
tr
</td>
<td style="text-align:right;">
957
</td>
</tr>
<tr>
<td style="text-align:left;">
de
</td>
<td style="text-align:right;">
570
</td>
</tr>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
72
</td>
</tr>
<tr>
<td style="text-align:left;">
und
</td>
<td style="text-align:right;">
68
</td>
</tr>
<tr>
<td style="text-align:left;">
in
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
es
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
fr
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
tl
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Yikes! So my result from the previous post were totally biased in favour of the Sociology Conference. And what language is <code>&quot;und&quot;</code> and what about the joint collection?</p>
</blockquote>
<pre class="r"><code>joint_collection %&gt;% group_by(lang) %&gt;% count() %&gt;% 
  filter(n &gt; 2) %&gt;% arrange(desc(n)) %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
lang
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
de
</td>
<td style="text-align:right;">
3156
</td>
</tr>
<tr>
<td style="text-align:left;">
tr
</td>
<td style="text-align:right;">
957
</td>
</tr>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
540
</td>
</tr>
<tr>
<td style="text-align:left;">
und
</td>
<td style="text-align:right;">
166
</td>
</tr>
<tr>
<td style="text-align:left;">
nl
</td>
<td style="text-align:right;">
20
</td>
</tr>
<tr>
<td style="text-align:left;">
sv
</td>
<td style="text-align:right;">
6
</td>
</tr>
<tr>
<td style="text-align:left;">
es
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:left;">
in
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:left;">
fr
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
3
</td>
</tr>
</tbody>
</table>
<blockquote>
<p><code>lang == &quot;tr&quot;</code> and <code>lang == &quot;und&quot;</code> definitly need some closer inspection.</p>
</blockquote>
<blockquote>
<p>But before we do that, let’s subset only the Tweets from the conferences’ week. Maybe the Turkish and the German Sociology #dgs2018 did not overlap temporally…</p>
</blockquote>
<p>Fortunatly, <code>rtweet</code> has a really convenient time-series plotting function…</p>
<pre class="r"><code>dgs_collection %&gt;% filter(lang == &quot;tr&quot; | lang == &quot;de&quot;) %&gt;% 
  group_by(lang) %&gt;% 
  rtweet::ts_plot() +
    theme_minimal()</code></pre>
<p><img src="/post/2018-10-07-r-german-academic-twitter-pt-2-from-data-to-corpus-with-a-turkish-twist_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>… unfortunately, I didn’t use it last time…</p>
<blockquote>
<p>Key Learning: I could have avoided stepping into this trap if I had plotted the distribution of Tweets over time… Exploratory Data Analysis FTW.</p>
</blockquote>
<p>This is what I would’ve seen, if I had done it right:</p>
<pre class="r"><code>joint_collection %&gt;%
  group_by(Discipline) %&gt;% 
  rtweet::ts_plot() +
    theme_minimal()</code></pre>
<p><img src="/post/2018-10-07-r-german-academic-twitter-pt-2-from-data-to-corpus-with-a-turkish-twist_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<blockquote>
<p>See that left peak around the 20th? Arghhhh!</p>
</blockquote>
<p>Time to move on. As we have already set an upper time limit above (<code>filter(created_at &lt; &quot;2018-09-30&quot;)</code>), we now only have to include a lower time limit:</p>
<pre class="r"><code>joint_collection_week &lt;- joint_collection %&gt;% 
  filter(created_at &gt; &quot;2018-09-23&quot;)

joint_collection_week %&gt;%
  group_by(lang) %&gt;% 
  count() %&gt;%
  filter(n &gt; 2) %&gt;% 
  arrange(desc(n)) %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
lang
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
de
</td>
<td style="text-align:right;">
3068
</td>
</tr>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
522
</td>
</tr>
<tr>
<td style="text-align:left;">
und
</td>
<td style="text-align:right;">
120
</td>
</tr>
<tr>
<td style="text-align:left;">
tr
</td>
<td style="text-align:right;">
92
</td>
</tr>
<tr>
<td style="text-align:left;">
nl
</td>
<td style="text-align:right;">
19
</td>
</tr>
<tr>
<td style="text-align:left;">
sv
</td>
<td style="text-align:right;">
6
</td>
</tr>
<tr>
<td style="text-align:left;">
es
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
fr
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
3
</td>
</tr>
</tbody>
</table>
<p>Ok, that’s already better, but there are still 92 Turkish Tweets in the sample, and 120 Tweets for <code>lang == &quot;und&quot;</code>.</p>
<blockquote>
<p>It turns out, however, that <code>lang == &quot;und&quot;</code> (un)fortunatly means <code>language undefined</code> <a href="https://blog.twitter.com/developer/en_us/a/2013/introducing-new-metadata-for-tweets.html" target="_blank">cf. Twitter</a>…</p>
</blockquote>
<p>Let’s have a look at the remaining Turkish Tweets and then rebuild our corpora and the document-feature matrix.</p>
<pre class="r"><code>joint_collection_week %&gt;%
  filter(lang == &quot;tr&quot;) %&gt;%
  select(text) %&gt;% 
  head() %&gt;% # for website readability
  knitr::kable(format = &quot;html&quot;, digits = 2) </code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
text
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Çok şükür Allahım… #dgs2018 <a href="https://t.co/DAXRFoawzq" class="uri">https://t.co/DAXRFoawzq</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
Mimar sinan güzel sanatlarlı olduk be 😂 #Dgstercih #dgs2018
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs2018 derslerden muaf olmak için en çok 5 yıl önce ilgili programdan mezun olmak gerekir şartı var mı arkadaşlar????? Bilen birisi bilgilendirsin lütfen.
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs2018 AÖF lisans dersleri DGS muafiyetinde kullanıyor mu??
</td>
</tr>
<tr>
<td style="text-align:left;">
Bilgi Üniversitesi’nde 2000li arkadaşlarımla hazırlık okuyacağım. Yaşlı olmak kontenjanından dışlanmam umarım🙄 #dgs2018 <span class="citation">@BiLGiOfficial</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
4 puan ile iktisat kaybettim sizce ek tercihlerde yazsam çıkar mı?#dgs2018 #DGSekyerleştirme #dgs #DGSE #dgsmovie3 #dgs
</td>
</tr>
</tbody>
</table>
<p>So all the Tweets are exclusivly in Turkish, and it is more than appropriate to exclude them from our analysis here AND in my preceding blog post. (Update incoming!)</p>
<blockquote>
<p>But who’s going to tell the German Sociologists that my report from last week had to be corrected and that they didn’t perform that well, actually …!?</p>
</blockquote>
<blockquote>
<p>Key learning: Never rely on blind/nummeric analysises only. Always do some qualitative exploration and check for plausibility - even when it’s “only” for a blog!!!</p>
</blockquote>
</div>
<div id="removing-turkish-accounts" class="section level2">
<h2><span class="header-section-number">4.2</span> Removing Turkish accounts</h2>
<p>First, let’s get list of all the Users who where part of the Turkish #dgs2018 sample (and since I’ve updated the previous post, I have collected some Turkish hashtags for <code>lang==&quot;und&quot;</code>, so we’ll just re-use this filter here.)</p>
<pre class="r"><code>tr_user &lt;- dgs_collection %&gt;%
  filter(str_detect(text,&quot;yks2018|yksdil|dgsankara|cumhuriyetüniversitesi|DanceKafe&quot;) | lang == &quot;tr&quot;) %&gt;% 
  select(user_id) %&gt;% 
  distinct()
tr_user %&gt;% count() %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
529
</td>
</tr>
</tbody>
</table>
<p>Now, we’ll <code>anti_join()</code> the <code>dgs_collection</code> with this list</p>
<pre class="r"><code>dgs_collection %&gt;% anti_join(tr_user, by = &quot;user_id&quot;) %&gt;% count()</code></pre>
<pre><code>## # A tibble: 1 x 1
##       n
##   &lt;int&gt;
## 1   686</code></pre>
<p>Let’s compare with the simpler <code>filter(lang!=&quot;tr&quot;)</code> approach</p>
<pre class="r"><code>dgs_collection %&gt;% 
  filter(lang != &quot;tr&quot;) %&gt;% 
  count() %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
717
</td>
</tr>
</tbody>
</table>
<p>That’s a difference of another ~30 Tweets. Nice. We’ll use that in a minute.</p>
</div>
</div>
<div id="rebuild-the-corpus-without-tweets-with-langtr" class="section level1">
<h1><span class="header-section-number">5</span> Rebuild the Corpus without Tweets with <code>lang==&quot;tr&quot;</code></h1>
<blockquote>
<p>There is two ways to do that. One is lazy and one is more replication-friendly. I’ll mention the lazy one, but will continue with the more robust approach</p>
</blockquote>
<p><strong>The Lazy Way</strong></p>
<p>(Two lazy ways, actually)</p>
<p>As we know that the Turkish Tweets are exclusively in the Sociology Corpus, we could just rebuild the <code>dgs_corpus</code> and then rebuild the <code>joint_corpus</code> with:</p>
<pre class="r"><code>joint_corpus &lt;- dvpw_corpus + 
                dgs_corpus + 
                hist_corpus + 
                inf_corpus + 
                mixed_corpus</code></pre>
<p>An even easier way would be to filter out Turkish Tweets from the already existing <code>joint_corpus</code> with <code>quanteda::corpus_subset()</code>:</p>
<pre class="r"><code>joint_corpus %&gt;% corpus_subset(joint_corpus$documents$lang != &quot;tr&quot;)</code></pre>
<p>However, if you have been jumping back and forth within this post (or <code>.Rmd</code> Notebook), then you (=me) might have lost track of the various manipulations and state differences (i.e. think of <code>custom_stopwords</code>). Plus, your <code>dgs_corpus</code> would still need our attention, too, and as we’ve filtered out a lot of Tweets by setting a lower time limit, the common time period for the corpora would differ, too. BAD!</p>
<blockquote>
<p>So let’s rebuild the corpora from scratch.</p>
</blockquote>
<div id="re-build-individual-corpora-from-scratch" class="section level2">
<h2><span class="header-section-number">5.1</span> Re-Build individual Corpora from Scratch</h2>
<p>We’ll just add <code>filter(created_at &gt; &quot;2018-09-23&quot;)</code> and for the sake of robustness, we’ll filter all corpora for <code>lang != &quot;tr&quot;</code>, and <code>anti_join(tr_user)</code> with the <code>dgs_corpus</code></p>
<p><strong>As I want both, discipline-specific copora with “multidisciplinary Tweets” and a redundancy-free joint corpus, I’ll build the corpora in two steps.</strong></p>
<pre class="r"><code>dvpw_corpus &lt;- dvpw_collection %&gt;% 
  filter(created_at &gt; &quot;2018-09-23&quot; &amp; lang != &quot;tr&quot;) %&gt;% # combined filter()
  # anti_join(mixed_collection, by = &quot;status_id&quot;) %&gt;% 
  corpus(docid_field = &quot;status_id&quot;, text_field = &quot;text&quot;)
  ## not totally sure about the effect of setting text_field = &quot;text&quot;
docvars(dvpw_corpus, &quot;Discipline&quot;) &lt;- &quot;PolSci&quot;

dgs_corpus &lt;- dgs_collection %&gt;% 
  filter(created_at &gt; &quot;2018-09-23&quot; &amp; lang != &quot;tr&quot;) %&gt;%
  # anti_join(mixed_collection, by = &quot;status_id&quot;) %&gt;%
  anti_join(tr_user, by = &quot;user_id&quot;) %&gt;% 
  corpus(docid_field = &quot;status_id&quot;, text_field = &quot;text&quot;)
docvars(dgs_corpus, &quot;Discipline&quot;) &lt;- &quot;Sociology&quot;

hist_corpus &lt;- hist_collection %&gt;% 
  filter(created_at &gt; &quot;2018-09-23&quot; &amp; lang != &quot;tr&quot;) %&gt;%
  # anti_join(mixed_collection, by = &quot;status_id&quot;) %&gt;% 
  corpus(docid_field = &quot;status_id&quot;, text_field = &quot;text&quot;)
docvars(hist_corpus, &quot;Discipline&quot;) &lt;- &quot;History&quot;

inf_corpus &lt;- inf_collection %&gt;% 
  filter(created_at &gt; &quot;2018-09-23&quot; &amp; lang != &quot;tr&quot;) %&gt;%
  # anti_join(mixed_collection, by = &quot;status_id&quot;) %&gt;% 
  corpus(docid_field = &quot;status_id&quot;, text_field = &quot;text&quot;)
docvars(inf_corpus, &quot;Discipline&quot;) &lt;- &quot;CS&quot;

mixed_corpus &lt;- mixed_collection %&gt;% 
  filter(created_at &gt; &quot;2018-09-23&quot; &amp; lang != &quot;tr&quot;) %&gt;%
  corpus(docid_field = &quot;status_id&quot;, text_field = &quot;text&quot;) # 42 docs!
docvars(mixed_corpus, &quot;Discipline&quot;) &lt;- &quot;Mixed&quot;</code></pre>
<blockquote>
<p>Of course, eventually, we should update and <code>rm()</code> all the obselete *_collection objects or simply consolidate all the “valid” Tweets in a .rds file. However, I’m not so much into editing raw-ish / original data, so doing that is up to you.</p>
</blockquote>
</div>
<div id="create-joint-corpus-1" class="section level2">
<h2><span class="header-section-number">5.2</span> Create Joint Corpus</h2>
<pre class="r"><code>joint_corpus &lt;- dvpw_corpus + 
                dgs_corpus + 
                hist_corpus + 
                inf_corpus # 3,748 docs

joint_corpus &lt;- joint_corpus %&gt;% corpus_subset(!(docnames(joint_corpus) %in% mixed_collection$status_id)) # 3,706 docs

joint_corpus &lt;- joint_corpus + mixed_corpus #3,748 docs</code></pre>
</div>
</div>
<div id="rd-attempt-dfm-building" class="section level1">
<h1><span class="header-section-number">6</span> 3rd Attempt @ <code>dfm()</code> Building</h1>
<pre class="r"><code>joint_dfm &lt;- dfm(joint_corpus,
                # groups = &quot;Discipline&quot;,
                 remove = c(stopwords(&quot;german&quot;),
                            stopwords(&quot;english&quot;),
                            custom_stopwords,
                            min_nchar = 3),
                 remove_punct = TRUE,
                 remove_url = TRUE,
                # remove_numbers = TRUE,
                 tolower = TRUE,
                 verbose = TRUE)</code></pre>
<pre><code>## Creating a dfm from a corpus input...</code></pre>
<pre><code>##    ... lowercasing</code></pre>
<pre><code>##    ... found 3,748 documents, 16,371 features</code></pre>
<pre><code>##    ... removed 608 features
##    ... created a 3,748 x 15,763 sparse dfm
##    ... complete. 
## Elapsed time: 0.42 seconds.</code></pre>
<p>We’re down to 15763 features from 3748 documents (Tweets) and were able to get rid of 608 features with the iteratively refined approach.</p>
<p>And as we might want to use a grouped dfm for group comparisons (and <code>dfm_group</code> doesn’t seem to work for me here), we’ll create a custom grouped one, too.</p>
<pre class="r"><code>## not working:
# dfm_group(joint_dfm, groups = &quot;Discipline&quot;)
# OR
# dfm_group(joint_dfm, groups = c(&quot;Discipline&quot;))
# OR
# dfm_group(joint_dfm, groups = docvars(joint_dfm, &quot;Discipline&quot;))
#&gt; Error in qatd_cpp_is_grouped_numeric(as.numeric(x), group) : 
#&gt;  (list) object cannot be coerced to type &#39;double&#39;

joint_dfm_grouped &lt;- dfm(joint_corpus,
                 groups = &quot;Discipline&quot;,
                 remove = c(stopwords(&quot;german&quot;),
                            stopwords(&quot;english&quot;),
                            custom_stopwords,
                            min_nchar = 3),
                 remove_punct = TRUE,
                 remove_url = TRUE,
                # remove_numbers = TRUE,
                 tolower = TRUE,
                 verbose = FALSE) #for website readability</code></pre>
</div>
<div id="some-quick-analyses" class="section level1">
<h1><span class="header-section-number">7</span> Some quick Analyses</h1>
<div id="top-features-per-discipline" class="section level2">
<h2><span class="header-section-number">7.1</span> Top Features per Discipline</h2>
<pre class="r"><code>topfeatures(joint_dfm, 20, groups = &quot;Discipline&quot;) # %&gt;% map(unlist) %&gt;% map(knitr::kable)</code></pre>
<pre><code>## $PolSci
##             #dvpw18       @dvpwkongress          demokratie 
##                1604                 146                 130 
##           #dvpw2018               @dvpw               panel 
##                 108                 107                 105 
##           democracy          @goetheuni           frankfurt 
##                  84                  69                  60 
##           political             grenzen          steinmeier 
##                  51                  49                  47 
## politikwissenschaft         #demokratie          democratic 
##                  45                  43                  41 
##         #steinmeier #departmentstruktur            kongress 
##                  41                  41                  38 
##                rede               #dvpw 
##                  36                  35 
## 
## $Sociology
##        #dgs18      #dgs2018 @dgsoziologie    soziologie   #soziologie 
##           576           131            86            55            38 
##       vortrag       #dvpw18      kongress     #sozkon18     göttingen 
##            32            29            26            26            23 
##         panel     spannende    #göttingen  gesellschaft        gruppe 
##            17            17            16            15            15 
##            et       session          raum        plenum             2 
##            14            14            14            14            13 
## 
## $History
##              #histag18         @historikertag     #historikertag2018 
##                   1004                     98                     81 
##                münster                sektion               #münster 
##                     67                     56                     51 
##             historiker             @vhdtweets          historikertag 
##                     49                     43                     41 
##               digitale             geschichte                  panel 
##                     40                     36                     33 
##                     de          #histocamptag                @digigw 
##                     33                     33                     32 
## geschichtswissenschaft                  stand                 poster 
##                     30                     29                     29 
##                  thema             #archivtag 
##                     28                     26 
## 
## $CS
## #informatik2018         #berlin        #zetsche      #frankfurt 
##             307              42              33              32 
##         #bremen           #jena       #dortmund      #kontrolle 
##              32              32              32              32 
##      #kanzlerin         #hessen     #nrwtag2018         #bayern 
##              32              32              32              32 
##  #niedersachsen    #brandenburg       #saarland          #baden 
##              32              32              32              32 
##    #württemberg          #koeln       #muenchen        #dresden 
##              32              32              32              32 
## 
## $Mixed
##       #dvpw18        #dgs18     #histag18 @dvpwkongress         woche 
##            38            30            25             4             3 
##        findet        tweets       minuten         gibts     digitalen 
##             3             3             3             3             3 
##      #dgs2018    #infdh2018         @dvpw     frankfurt        kolleg 
##             3             3             2             2             2 
##     #dvpw2018         sehen kongresswoche             1          good 
##             2             2             2             2             2</code></pre>
<blockquote>
<p>There are still a couple features which would qualify for being removed (such as “unsere”, “mal”, “schon”), but we will take care of that with the super-useful <code>quanteda::dfm_trim(&lt;term_freq&gt;)</code> threshold-based feature selection.</p>
</blockquote>
<blockquote>
<p>Plus, removing or parsing hashtags and applying <code>dfm(stem = TRUE)</code> would largely increase descriptive accuracy</p>
</blockquote>
</div>
<div id="hashtags" class="section level2">
<h2><span class="header-section-number">7.2</span> Hashtags</h2>
<p><strong>Most popular hashtags by absolute numbers:</strong></p>
<pre class="r"><code>hashtags_dfm &lt;- dfm_select(joint_dfm, (&#39;#*&#39;))
topfeatures(hashtags_dfm, 20, scheme = &quot;count&quot;) %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
x
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
#dvpw18
</td>
<td style="text-align:right;">
1694
</td>
</tr>
<tr>
<td style="text-align:left;">
#histag18
</td>
<td style="text-align:right;">
1043
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs18
</td>
<td style="text-align:right;">
622
</td>
</tr>
<tr>
<td style="text-align:left;">
#informatik2018
</td>
<td style="text-align:right;">
313
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs2018
</td>
<td style="text-align:right;">
136
</td>
</tr>
<tr>
<td style="text-align:left;">
#dvpw2018
</td>
<td style="text-align:right;">
113
</td>
</tr>
<tr>
<td style="text-align:left;">
#historikertag2018
</td>
<td style="text-align:right;">
84
</td>
</tr>
<tr>
<td style="text-align:left;">
#münster
</td>
<td style="text-align:right;">
53
</td>
</tr>
<tr>
<td style="text-align:left;">
#frankfurt
</td>
<td style="text-align:right;">
46
</td>
</tr>
<tr>
<td style="text-align:left;">
#demokratie
</td>
<td style="text-align:right;">
45
</td>
</tr>
<tr>
<td style="text-align:left;">
#berlin
</td>
<td style="text-align:right;">
45
</td>
</tr>
<tr>
<td style="text-align:left;">
#digitalisierung
</td>
<td style="text-align:right;">
43
</td>
</tr>
<tr>
<td style="text-align:left;">
#steinmeier
</td>
<td style="text-align:right;">
41
</td>
</tr>
<tr>
<td style="text-align:left;">
#departmentstruktur
</td>
<td style="text-align:right;">
41
</td>
</tr>
<tr>
<td style="text-align:left;">
#soziologie
</td>
<td style="text-align:right;">
38
</td>
</tr>
<tr>
<td style="text-align:left;">
#zetsche
</td>
<td style="text-align:right;">
36
</td>
</tr>
<tr>
<td style="text-align:left;">
#dvpw
</td>
<td style="text-align:right;">
35
</td>
</tr>
<tr>
<td style="text-align:left;">
#jena
</td>
<td style="text-align:right;">
34
</td>
</tr>
<tr>
<td style="text-align:left;">
#bremen
</td>
<td style="text-align:right;">
33
</td>
</tr>
<tr>
<td style="text-align:left;">
#histocamptag
</td>
<td style="text-align:right;">
33
</td>
</tr>
</tbody>
</table>
<p><strong>Most popular hashtags by absolute numbers per Discipline:</strong></p>
<pre class="r"><code>topfeatures(hashtags_dfm, 20, group = &quot;Discipline&quot;, scheme = &quot;count&quot;)</code></pre>
<pre><code>## $PolSci
##              #dvpw18            #dvpw2018          #demokratie 
##                 1604                  108                   43 
##          #steinmeier  #departmentstruktur                #dvpw 
##                   41                   41                   35 
##                #powi     #bundespräsident #politikwissenschaft 
##                   26                   26                   25 
##           #democracy            #takeover           #powilehre 
##                   23                   17                   15 
##           #frankfurt        #energiewende        #servicetweet 
##                   14                   12                    9 
##            #populism     #twittertakeover      #janemansbridge 
##                    9                    9                    9 
##             #keynote             #polisci 
##                    9                    7 
## 
## $Sociology
##              #dgs18            #dgs2018         #soziologie 
##                 576                 131                  38 
##             #dvpw18           #sozkon18          #göttingen 
##                  29                  26                  16 
##           #histag18                #dgs        #dgskongress 
##                  12                  11                  10 
##        #integration #soziologiekongress       #mixedmethods 
##                   9                   9                   8 
##    #digitalisierung             #flucht          #migration 
##                   7                   7                   6 
##    #forschungsethik         #sozkon2018            #sfb1265 
##                   6                   5                   4 
##            #luhmann             #simmel 
##                   4                   4 
## 
## $History
##          #histag18 #historikertag2018           #münster 
##               1004                 81                 51 
##      #histocamptag         #archivtag            #dvpw18 
##                 33                 26                 21 
##     #historikertag  #doktorandenforum             #dgs18 
##                 19                 15                 14 
##   #twitterstorians   #forschungsdaten        #geschichte 
##                 13                 11                 11 
## #digitalhumanities           #auxhist            #digigw 
##                 11                 11                 10 
##       #gtshistag18        #openaccess   #digitalisierung 
##                  9                  8                  8 
##          #muenster        #histag2018 
##                  8                  8 
## 
## $CS
## #informatik2018         #berlin        #zetsche      #frankfurt 
##             307              42              33              32 
##         #bremen           #jena       #dortmund      #kontrolle 
##              32              32              32              32 
##      #kanzlerin         #hessen     #nrwtag2018         #bayern 
##              32              32              32              32 
##  #niedersachsen    #brandenburg       #saarland          #baden 
##              32              32              32              32 
##    #württemberg          #koeln       #muenchen        #dresden 
##              32              32              32              32 
## 
## $Mixed
##            #dvpw18             #dgs18          #histag18 
##                 38                 30                 25 
##           #dgs2018         #infdh2018          #dvpw2018 
##                  3                  3                  2 
##           #daimler    #informatik2018         #archivtag 
##                  2                  2                  2 
##           #gfm2018 #historikertag2018            #kauder 
##                  2                  2                  2 
##            #fcbfca              #powi               #gew 
##                  2                  1                  1 
##         #göttingen            #türkei           #twitter 
##                  1                  1                  1 
##       #hambibleibt    #hambacherforst 
##                  1                  1</code></pre>
<blockquote>
<p>~The Sociology Corpus has still some Turkish features. There are ways to adress this, but I have to post-pone this for another post.~</p>
</blockquote>
<p><strong>Most popular Hashtags by shared <code>docfreq</code> / feature-document frequency:</strong></p>
<pre class="r"><code>dfm_select(joint_dfm_grouped, (&#39;#*&#39;)) %&gt;% 
  topfeatures(30, scheme = &quot;docfreq&quot;) %&gt;% 
  knitr::kable(format = &quot;html&quot;, digits = 2)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
x
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
#dvpw18
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:left;">
#histag18
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:left;">
#informatik2018
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:left;">
#powi
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
#dvpw2018
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
#göttingen
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
#archivtag
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
#twitter
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
#digitalisierung
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
#afd
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
#sozialwissenschaften
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
#dgs18
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
#infdh2018
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
#gfm2018
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
#servicetweet
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
#gew
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
#türkei
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
#daimler
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
#berlin
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
#hambibleibt
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
#hambacherforst
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
#nachhaltigkeit
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
#openaccess
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
#migration
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
#darkphoenix
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
#facebookdown
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
#innsbrucktirol2018
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
#bigdata
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
#spd
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
#ff
</td>
<td style="text-align:right;">
3
</td>
</tr>
</tbody>
</table>
</div>
<div id="network-of-feature-co-occurrences" class="section level2">
<h2><span class="header-section-number">7.3</span> Network of feature co-occurrences</h2>
<pre class="r"><code>topfeats &lt;- names(topfeatures(joint_dfm, 60))
textplot_network(dfm_select(joint_dfm, topfeats), min_freq = 0.8)</code></pre>
<p><img src="/post/2018-10-07-r-german-academic-twitter-pt-2-from-data-to-corpus-with-a-turkish-twist_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
</div>
<div id="grouped-wordcloud-of-features" class="section level2">
<h2><span class="header-section-number">7.4</span> Grouped wordcloud of features</h2>
<blockquote>
<p>“wordcloud, where the feature labels are plotted with their sizes proportional to their numerical values in the dfm” (Vignette for <code>quanteda::textplot_wordcloud</code>)</p>
</blockquote>
<pre class="r"><code>textplot_wordcloud(joint_dfm_grouped,
                   comparison = TRUE,
                   min_size = 0.5,
                   max_size = 3,
                   max_words = 60)</code></pre>
<p><img src="/post/2018-10-07-r-german-academic-twitter-pt-2-from-data-to-corpus-with-a-turkish-twist_files/figure-html/unnamed-chunk-41-1.png" width="960" /></p>
</div>
</div>
<div id="whats-next" class="section level1">
<h1><span class="header-section-number">8</span> What’s next?</h1>
<blockquote>
<p>Topic Modelling!</p>
</blockquote>
<p>Now that I had to spend quite an amount of time on data processing, cleaning, and eventually building a usable <code>dfm</code>, the actual analysis of the contents remains a #TODO</p>
<blockquote>
<p>However, I learned a lot doing this today, and I hope that it became obvious that dealing with text as data is not to be underestimated.</p>
</blockquote>
</div>
