---
title: 'Election Hacking: Exploring 10 Million Tweets from the Russian Internet Research
  Agency Dataset, Pt. 1'
author: Ilja / fubits
date: '2018-10-26'
slug: election-hacking-exploring-2-million-tweets-from-the-russian-internet-research-agency-dataset-pt-1
categories:
  - Rstats
  - DataViz
  - Natural Language Processing NLP
tags:
  - ggplot
  - Twitter
  - CSV
output:
  blogdown::html_page:
    number_sections: yes
    toc: yes
lastmod: '2018-10-26T16:18:07+02:00'
description: "A bit over a week ago, Twitter's new-ish Elections integrity team released two datasets with 'all the accounts and related content associated with potential information operations that we have found on our service since 2016.' We're talking about millions of Tweets in dozens of languages stored in a single 5.3 GB CSV file. Tidyverse to the rescue!" 
abstract: 'Post updated with data from the full 5.3GB CSV file from the "Internet Research Agency" dataset'
thumbnail: "/img/thumbs/IRA_Tweets.jpg"
rmdlink: yes
keywords: []
comment: no
autoCollapseToc: no
postMetaInFooter: no
hiddenFromHomePage: no
contentCopyright: no
reward: no
mathjax: no
mathjaxEnableSingleDollar: no
mathjaxEnableAutoNumber: no
hideHeaderAndFooter: no
flowchartDiagrams:
  enable: no
  options: ''
sequenceDiagrams:
  enable: no
  options: ''
---


<div id="TOC">
<ul>
<li><a href="#data-preperation"><span class="toc-section-number">1</span> Data Preperation</a><ul>
<li><a href="#change-variable-types"><span class="toc-section-number">1.1</span> Change Variable Types</a></li>
<li><a href="#remove-duplicates"><span class="toc-section-number">1.2</span> Remove Duplicates</a></li>
<li><a href="#reducerecode-language-variables"><span class="toc-section-number">1.3</span> Reduce/Recode Language Variables</a></li>
<li><a href="#ira-dataset-languages-summary"><span class="toc-section-number">1.4</span> IRA Dataset Languages: Summary</a></li>
</ul></li>
<li><a href="#who-tweeted-in-what-language"><span class="toc-section-number">2</span> Who tweeted in what language?</a><ul>
<li><a href="#create-language-specific-subsets"><span class="toc-section-number">2.1</span> Create Language-specific Subsets</a></li>
<li><a href="#summary-plots-languages-general-activity"><span class="toc-section-number">2.2</span> Summary Plots: Languages &amp; General Activity</a><ul>
<li><a href="#consolidating-tweet-languages-per-account"><span class="toc-section-number">2.2.1</span> Consolidating Tweet Languages per Account</a></li>
<li><a href="#general-activity-plots"><span class="toc-section-number">2.2.2</span> General Activity Plots</a></li>
</ul></li>
<li><a href="#languages-accounts-vs-tweets"><span class="toc-section-number">2.3</span> Languages: Accounts vs Tweets</a></li>
</ul></li>
</ul>
</div>

<div class="figure">
<img src="/img/IRA_dataset/IRA_Tweets_Dates.png" alt="(Creation Date of Top 15 Accounts in the IRA Dataset)" style="width:100.0%" />
<p class="caption"><em>(Creation Date of Top 15 Accounts in the IRA Dataset)</em></p>
</div>
<p>A bit over a week ago, <a href="https://blog.twitter.com/official/en_us/topics/company/2018/enabling-further-research-of-information-operations-on-twitter.html" target="_blank">Twitter’s new-ish Elections integrity team released two datasets</a> with “all the accounts and related content associated with potential information operations that we have found on our service since 2016.”</p>
<p>In particular, this is what we are talking about:</p>
<blockquote>
<p>“Our initial disclosures cover two previously disclosed campaigns, and include information from 3,841 accounts believed to be connected to the Russian Internet Research Agency [also known as IRA], and 770 accounts believed to originate in Iran.” (<a href="https://blog.twitter.com/official/en_us/topics/company/2018/enabling-further-research-of-information-operations-on-twitter.html" target="_blank">Twitter’s Election Integrity Team</a>)</p>
</blockquote>
<p>For a bit of a context on the IRA’s activities and the Russian Influence Operation in general, <a href="https://mashable.com/article/russian-trolls-spies-operatives/?europe=true&amp;geo=AS&amp;utm_cid=mash-prod-nav-geo#7pbvrw1_DaqI" target="_blank">Mashable</a> offers a nice overview.</p>
<p>The IRA zip alone is <strong>1.24 GB</strong> big! Let’s dive in and explore. Before we can start with any analysis, automated or not, we have to inspect and prepare the data - remember: <a href="https://ellocke.github.io/post/r-german-academic-twitter-pt-2-from-data-to-corpus-with-a-turkish-twist/#the-turkish-plot-twist">EDA FTW</a>!</p>
<p>Anyways, a dataset of this size is a perfect exercise in data wrangling and exploratory analysis with tools from the galactic <code>tidyverse</code>. So what I’m aiming to highlight with this post, is my more or less systematic approach to turning an granular dataset with millions of observations into something more useful (and reliable!) for further in-depth analysis.</p>
<div id="data-preperation" class="section level1">
<h1><span class="header-section-number">1</span> Data Preperation</h1>
<p>You can get the data from here:</p>
<ul>
<li>source: <a href="https://about.twitter.com/en_us/values/elections-integrity.html#data" class="uri">https://about.twitter.com/en_us/values/elections-integrity.html#data</a></li>
<li>IRA CSV ZIP: <a href="https://storage.googleapis.com/twitter-election-integrity/hashed/ira/ira_tweets_csv_hashed.zip" class="uri">https://storage.googleapis.com/twitter-election-integrity/hashed/ira/ira_tweets_csv_hashed.zip</a></li>
<li>README: <a href="https://storage.googleapis.com/twitter-election-integrity/hashed/Twitter_Elections_Integrity_Datasets_hashed_README.txt" class="uri">https://storage.googleapis.com/twitter-election-integrity/hashed/Twitter_Elections_Integrity_Datasets_hashed_README.txt</a></li>
</ul>
<pre class="r"><code>library(tidyverse)</code></pre>
<p>First, we need to unpack the <code>.zip</code> file and then read the <code>.csv</code> file into R.</p>
<pre class="r"><code>csvfile &lt;- &quot;ira_tweets_csv_hashed.csv&quot;
data_raw &lt;- read_csv(&quot;ira_tweets_csv_hashed.csv&quot;)

# Just for comparison
data2_raw &lt;- data.table::fread(csvfile,
                          encoding = &quot;UTF-8&quot;,
                          # na.strings = &quot;,,&quot;,
                          verbose = TRUE)</code></pre>
<blockquote>
<p>At first – I (<a href="https://twitter.com/avuko/status/1052573187869986816" target="_blank">like others</a>) – was getting an CRC error message when unpacking the zip file. The resulting CSV was only 1.17 GB big, so that were not all the Tweets from the IRA dataset. After upgrading <code>7-zip</code> to <code>v18.05</code> unpacking the <code>zip</code> results in a 5.3 GB big CSV, which is quite a difference I’d say :)</p>
</blockquote>
<blockquote>
<p><code>data.table</code> is by light years the fastest method, but <code>read_csv()</code> gives me <code>NA</code>’s without an extra hassle while <code>data.table::fread()</code> seems to be ignoring any patterns for <code>na.strings</code>. Therefore I’ll be working with the data object from <code>read_csv()</code> here. Since <code>read_csv()</code> is rather slow with a <code>CSV</code> this big, you can speed up your exploration if you save the data object as an <code>.rds</code> or <code>.RData</code> file.</p>
</blockquote>
<pre class="r"><code>data_path &lt;- here::here(&quot;static&quot;, &quot;data&quot;, &quot;IRA_Tweets&quot;, &quot;/&quot;)
# if (!dir.exists(data_path)) dir.create(data_path)
# saveRDS(data_raw, str_c(data_path, &quot;infoops_data.rds&quot;))
# save(data_raw, file = str_c(data_path, &quot;infoops_data.RData&quot;))
data_raw &lt;- readRDS(str_c(data_path, &quot;infoops_data.rds&quot;))</code></pre>
<p>With a dataset this big, skimr::skim() is just perfect (and it’s output much more functional in RStudio)!</p>
<pre class="r"><code>data_raw %&gt;% skimr::skim_to_wide() %&gt;% knitr::kable(&quot;html&quot;)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
type
</th>
<th style="text-align:left;">
variable
</th>
<th style="text-align:left;">
missing
</th>
<th style="text-align:left;">
complete
</th>
<th style="text-align:left;">
n
</th>
<th style="text-align:left;">
min
</th>
<th style="text-align:left;">
max
</th>
<th style="text-align:left;">
empty
</th>
<th style="text-align:left;">
n_unique
</th>
<th style="text-align:left;">
median
</th>
<th style="text-align:left;">
mean
</th>
<th style="text-align:left;">
sd
</th>
<th style="text-align:left;">
p0
</th>
<th style="text-align:left;">
p25
</th>
<th style="text-align:left;">
p50
</th>
<th style="text-align:left;">
p75
</th>
<th style="text-align:left;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
account_language
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
11
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
hashtags
</td>
<td style="text-align:left;">
2378775
</td>
<td style="text-align:left;">
6662533
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
156
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
244865
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
in_reply_to_userid
</td>
<td style="text-align:left;">
8503421
</td>
<td style="text-align:left;">
537887
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
64
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
82809
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
is_retweet
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
latitude
</td>
<td style="text-align:left;">
9036529
</td>
<td style="text-align:left;">
4779
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
19
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
2752
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
longitude
</td>
<td style="text-align:left;">
9036529
</td>
<td style="text-align:left;">
4779
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
2807
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
poll_choices
</td>
<td style="text-align:left;">
9040172
</td>
<td style="text-align:left;">
1136
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
80
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
708
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
retweet_userid
</td>
<td style="text-align:left;">
5708124
</td>
<td style="text-align:left;">
3333184
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
64
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
204289
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
tweet_client_name
</td>
<td style="text-align:left;">
40341
</td>
<td style="text-align:left;">
9000967
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
32
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
333
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
tweet_language
</td>
<td style="text-align:left;">
296106
</td>
<td style="text-align:left;">
8745202
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
58
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
tweet_text
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
710
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
6598905
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
urls
</td>
<td style="text-align:left;">
1640484
</td>
<td style="text-align:left;">
7400824
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
2057
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
2760160
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
user_display_name
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
64
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
3664
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
user_mentions
</td>
<td style="text-align:left;">
5047231
</td>
<td style="text-align:left;">
3994077
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
808
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
570293
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
user_profile_description
</td>
<td style="text-align:left;">
1371499
</td>
<td style="text-align:left;">
7669809
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
160
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
2597
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
user_profile_url
</td>
<td style="text-align:left;">
7146952
</td>
<td style="text-align:left;">
1894356
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
22
</td>
<td style="text-align:left;">
23
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
200
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
user_reported_location
</td>
<td style="text-align:left;">
1526654
</td>
<td style="text-align:left;">
7514654
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
30
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
608
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
user_screen_name
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
6
</td>
<td style="text-align:left;">
64
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
3667
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
userid
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
9
</td>
<td style="text-align:left;">
64
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
3667
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Date
</td>
<td style="text-align:left;">
account_creation_date
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
2009-04-24
</td>
<td style="text-align:left;">
2018-04-03
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
653
</td>
<td style="text-align:left;">
2014-03-28
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
integer
</td>
<td style="text-align:left;">
follower_count
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
8670.2
</td>
<td style="text-align:left;">
22146.39
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
346
</td>
<td style="text-align:left;">
842
</td>
<td style="text-align:left;">
4486
</td>
<td style="text-align:left;">
257638
</td>
<td style="text-align:left;">
▇▁▁▁▁▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
integer
</td>
<td style="text-align:left;">
following_count
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
2522.47
</td>
<td style="text-align:left;">
5028.83
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
284
</td>
<td style="text-align:left;">
618
</td>
<td style="text-align:left;">
2014
</td>
<td style="text-align:left;">
74664
</td>
<td style="text-align:left;">
▇▁▁▁▁▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
integer
</td>
<td style="text-align:left;">
like_count
</td>
<td style="text-align:left;">
2673
</td>
<td style="text-align:left;">
9038635
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
290.31
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
325826
</td>
<td style="text-align:left;">
▇▁▁▁▁▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
integer
</td>
<td style="text-align:left;">
quote_count
</td>
<td style="text-align:left;">
2673
</td>
<td style="text-align:left;">
9038635
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
0.2
</td>
<td style="text-align:left;">
13.07
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
11633
</td>
<td style="text-align:left;">
▇▁▁▁▁▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
integer
</td>
<td style="text-align:left;">
reply_count
</td>
<td style="text-align:left;">
2673
</td>
<td style="text-align:left;">
9038635
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
0.28
</td>
<td style="text-align:left;">
7.41
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
3249
</td>
<td style="text-align:left;">
▇▁▁▁▁▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
integer
</td>
<td style="text-align:left;">
retweet_count
</td>
<td style="text-align:left;">
2673
</td>
<td style="text-align:left;">
9038635
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
3.46
</td>
<td style="text-align:left;">
140.33
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
123617
</td>
<td style="text-align:left;">
▇▁▁▁▁▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
in_reply_to_tweetid
</td>
<td style="text-align:left;">
8775100
</td>
<td style="text-align:left;">
266208
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
6.1e+17
</td>
<td style="text-align:left;">
1.3e+17
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
5.7e+17
</td>
<td style="text-align:left;">
6.3e+17
</td>
<td style="text-align:left;">
6.6e+17
</td>
<td style="text-align:left;">
1e+18
</td>
<td style="text-align:left;">
▁▁▁▁▆▇▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
quoted_tweet_tweetid
</td>
<td style="text-align:left;">
8853395
</td>
<td style="text-align:left;">
187913
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
8e+17
</td>
<td style="text-align:left;">
8.7e+16
</td>
<td style="text-align:left;">
1.8e+09
</td>
<td style="text-align:left;">
7.7e+17
</td>
<td style="text-align:left;">
8.1e+17
</td>
<td style="text-align:left;">
8.5e+17
</td>
<td style="text-align:left;">
1e+18
</td>
<td style="text-align:left;">
▁▁▁▁▁▂▇▂
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
retweet_tweetid
</td>
<td style="text-align:left;">
5708124
</td>
<td style="text-align:left;">
3333184
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
6.7e+17
</td>
<td style="text-align:left;">
1.2e+17
</td>
<td style="text-align:left;">
100
</td>
<td style="text-align:left;">
5.7e+17
</td>
<td style="text-align:left;">
6.5e+17
</td>
<td style="text-align:left;">
7.9e+17
</td>
<td style="text-align:left;">
1e+18
</td>
<td style="text-align:left;">
▁▁▁▁▇▅▆▁
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
tweetid
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
6.4e+17
</td>
<td style="text-align:left;">
1.6e+17
</td>
<td style="text-align:left;">
1.7e+09
</td>
<td style="text-align:left;">
5.3e+17
</td>
<td style="text-align:left;">
6.2e+17
</td>
<td style="text-align:left;">
7.8e+17
</td>
<td style="text-align:left;">
1e+18
</td>
<td style="text-align:left;">
▁▁▁▃▇▅▅▁
</td>
</tr>
<tr>
<td style="text-align:left;">
POSIXct
</td>
<td style="text-align:left;">
tweet_time
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
2009-05-09
</td>
<td style="text-align:left;">
2018-06-21
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
1788062
</td>
<td style="text-align:left;">
2015-07-17
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
</tbody>
</table>
<p>We can already make some interesting observations from this summary alone:</p>
<ul>
<li>The IRA dataset consist of <del>1.899.595</del> 9.041.308 Tweets in <del>51</del> 58 languages, from <del>3.460</del> 3.667 unique accounts and 11 account languages. That’s pretty “diverse” but also quite complex.</li>
<li><code>$is_retweet</code> has only 2 unique values, so it’s obviously a Boolean -&gt; <code>mutate()</code></li>
<li>There’s <del>1.899.595</del> 9.041.308 observations for <code>$tweet_text</code>, but only <del>1.634.942</del> 6.598.905 are unique. This huge delta just screams: spam bots and/or coordinated campaigns!</li>
<li>only <del>50K</del> 266K Tweets are replies -&gt; rather few interactions</li>
<li>there are some prominent accounts with up to 257K followers</li>
<li><del>743.828</del> 2.760.160 URLs to explore</li>
<li>we can see from <code>$retweet_userid</code> that apparently, <del>703.467</del> 3.333.184 Tweets are just Retweets and not unique/original Tweets.</li>
<li>if we were to try to classify accounts by profile description, there’s a corpus of <del>2.451</del> 2.597 unique profile descriptions (<code>$user_profile_description</code>) and 200 unique <code>$user_profile_url</code>s</li>
<li>all the <code>$*_tweetid</code> vars were read as numeric, which we’ll also need to change, as IDs are supposed to be unique identifiers and not continuous values -&gt; <code>mutate()</code></li>
<li>the Tweets were posted in the period from 2009-05-09 (!) to 2018-06-21, with the median around 2015-07-17</li>
<li>half of the accounts were created on or after 2014-03-28. Like there was an upcoming election or a referendum or something :)</li>
<li>there are 608 unique account locations (shared by an unknown number of those 3.667 accounts at this point), and there are 4.779 geolocated Tweets. That’s not much, but we could try to double-check these locations with the respective <code>$account_language</code> values.</li>
</ul>
<p>That should give us enough leads for an initial inquiry. Let’s continue with the data preparation and address what we have discovered so far.</p>
<div id="change-variable-types" class="section level2">
<h2><span class="header-section-number">1.1</span> Change Variable Types</h2>
<p><strong>convert <code>$is_retweet</code> into a boolean</strong></p>
<pre class="r"><code>data_raw$is_retweet &lt;- as.logical(data_raw$is_retweet)</code></pre>
<p><strong>convert <code>$*_tweetid</code> vars into strings</strong></p>
<pre class="r"><code>data_raw &lt;- data_raw %&gt;% 
  mutate_at(vars(ends_with(&quot;tweetid&quot;)),
            funs(as.character))</code></pre>
<p>Now we can <code>skim</code> just the <code>$*_tweetid</code> vars and <code>$is_retweet</code></p>
<pre class="r"><code>data_raw %&gt;% 
  select(is_retweet, ends_with(&quot;tweetid&quot;)) %&gt;% 
  skimr::skim_to_wide(noten_raw) %&gt;%
  knitr::kable(&quot;html&quot;)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
type
</th>
<th style="text-align:left;">
variable
</th>
<th style="text-align:left;">
missing
</th>
<th style="text-align:left;">
complete
</th>
<th style="text-align:left;">
n
</th>
<th style="text-align:left;">
min
</th>
<th style="text-align:left;">
max
</th>
<th style="text-align:left;">
empty
</th>
<th style="text-align:left;">
n_unique
</th>
<th style="text-align:left;">
mean
</th>
<th style="text-align:left;">
count
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
in_reply_to_tweetid
</td>
<td style="text-align:left;">
8775100
</td>
<td style="text-align:left;">
266208
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
19
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
236322
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
quoted_tweet_tweetid
</td>
<td style="text-align:left;">
8853395
</td>
<td style="text-align:left;">
187913
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
10
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
144609
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
retweet_tweetid
</td>
<td style="text-align:left;">
5708124
</td>
<td style="text-align:left;">
3333184
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
19
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
1725841
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
tweetid
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
10
</td>
<td style="text-align:left;">
19
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
9035946
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
logical
</td>
<td style="text-align:left;">
is_retweet
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
9041308
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
0.37
</td>
<td style="text-align:left;">
FAL: 5708124, TRU: 3333184, NA: 0
</td>
</tr>
</tbody>
</table>
<p>Ok, now we know that 3.333.184 (~1/3) Tweets are Retweets (of 1.725.841 unique Tweets). Good to know for any Natural Language Processing Method which depends on statistics, i.e. Topic Modelling, or when building a corpus for descriptive analyses.</p>
</div>
<div id="remove-duplicates" class="section level2">
<h2><span class="header-section-number">1.2</span> Remove Duplicates</h2>
<p>It’s probably more efficient to remove duplicates as the first step. This reduces the data object we’re working with.</p>
<pre class="r"><code>data_unique &lt;- data_raw %&gt;% filter(is_retweet == FALSE)</code></pre>
<p>Now we’re down to 5707611 unique Tweets in 57 Tweet languages by 3548 Users with 11 account languages.</p>
</div>
<div id="reducerecode-language-variables" class="section level2">
<h2><span class="header-section-number">1.3</span> Reduce/Recode Language Variables</h2>
<p><strong>$tweet_language</strong></p>
<pre class="r"><code>data_unique %&gt;% 
  group_by(tweet_language) %&gt;% 
  count() %&gt;% 
  filter(n &gt; 1000) %&gt;% 
  arrange(desc(n)) %&gt;%
  knitr::kable(format = &quot;html&quot;)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
tweet_language
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
ru
</td>
<td style="text-align:right;">
2839622
</td>
</tr>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
2178309
</td>
</tr>
<tr>
<td style="text-align:left;">
NA
</td>
<td style="text-align:right;">
285539
</td>
</tr>
<tr>
<td style="text-align:left;">
und
</td>
<td style="text-align:right;">
119098
</td>
</tr>
<tr>
<td style="text-align:left;">
de
</td>
<td style="text-align:right;">
86259
</td>
</tr>
<tr>
<td style="text-align:left;">
uk
</td>
<td style="text-align:right;">
49889
</td>
</tr>
<tr>
<td style="text-align:left;">
bg
</td>
<td style="text-align:right;">
36576
</td>
</tr>
<tr>
<td style="text-align:left;">
ar
</td>
<td style="text-align:right;">
35811
</td>
</tr>
<tr>
<td style="text-align:left;">
es
</td>
<td style="text-align:right;">
8402
</td>
</tr>
<tr>
<td style="text-align:left;">
in
</td>
<td style="text-align:right;">
7543
</td>
</tr>
<tr>
<td style="text-align:left;">
fr
</td>
<td style="text-align:right;">
7501
</td>
</tr>
<tr>
<td style="text-align:left;">
sr
</td>
<td style="text-align:right;">
5604
</td>
</tr>
<tr>
<td style="text-align:left;">
tl
</td>
<td style="text-align:right;">
5176
</td>
</tr>
<tr>
<td style="text-align:left;">
ht
</td>
<td style="text-align:right;">
4944
</td>
</tr>
<tr>
<td style="text-align:left;">
et
</td>
<td style="text-align:right;">
4920
</td>
</tr>
<tr>
<td style="text-align:left;">
sk
</td>
<td style="text-align:right;">
2982
</td>
</tr>
<tr>
<td style="text-align:left;">
tr
</td>
<td style="text-align:right;">
2903
</td>
</tr>
<tr>
<td style="text-align:left;">
da
</td>
<td style="text-align:right;">
2699
</td>
</tr>
<tr>
<td style="text-align:left;">
ro
</td>
<td style="text-align:right;">
2517
</td>
</tr>
<tr>
<td style="text-align:left;">
it
</td>
<td style="text-align:right;">
2493
</td>
</tr>
<tr>
<td style="text-align:left;">
nl
</td>
<td style="text-align:right;">
2292
</td>
</tr>
<tr>
<td style="text-align:left;">
cy
</td>
<td style="text-align:right;">
2214
</td>
</tr>
<tr>
<td style="text-align:left;">
sl
</td>
<td style="text-align:right;">
2123
</td>
</tr>
<tr>
<td style="text-align:left;">
pt
</td>
<td style="text-align:right;">
1857
</td>
</tr>
<tr>
<td style="text-align:left;">
fi
</td>
<td style="text-align:right;">
1414
</td>
</tr>
<tr>
<td style="text-align:left;">
pl
</td>
<td style="text-align:right;">
1325
</td>
</tr>
<tr>
<td style="text-align:left;">
sv
</td>
<td style="text-align:right;">
1191
</td>
</tr>
<tr>
<td style="text-align:left;">
lt
</td>
<td style="text-align:right;">
1190
</td>
</tr>
<tr>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
1135
</td>
</tr>
<tr>
<td style="text-align:left;">
ja
</td>
<td style="text-align:right;">
1117
</td>
</tr>
</tbody>
</table>
<p>That’s quite a lot, even if we only consider Tweet languages with n &gt; 1000 Tweets.</p>
<p><strong>merge NA and und[defined]</strong></p>
<pre class="r"><code>data_unique &lt;- data_unique %&gt;% 
  mutate(tweet_language = if_else(is.na(tweet_language), &quot;und&quot;, tweet_language))</code></pre>
<p><strong>recode all langs with n &lt; 5000 as “other”</strong></p>
<p>We need to reduce the scope of Tweet languages for now. 5000 is only slightly less than 1% of the unique Tweets, so this sounds like a good threshold.</p>
<pre class="r"><code># I&#39;m very sure that there&#39;s a more elegant solution for mutating observations row-wise based on grouped counts... However, whatever works, works.

other_langs &lt;- data_unique %&gt;% 
  group_by(tweet_language) %&gt;% 
  count() %&gt;% 
  filter(n &lt; 5000) %&gt;% 
  select(tweet_language)</code></pre>
<pre class="r"><code>data_unique &lt;- data_unique %&gt;% 
  mutate(tweet_language = 
           if_else(tweet_language %in% other_langs$tweet_language, &quot;other_44&quot;,
                                  tweet_language))</code></pre>
<pre class="r"><code>n_distinct(data_unique$tweet_language)</code></pre>
<pre><code>## [1] 12</code></pre>
<p>We’re down to 13 language categories for the Tweets. That’s far better!</p>
<p><strong>$account_language</strong></p>
<pre class="r"><code>data_unique %&gt;% 
  group_by(account_language) %&gt;% 
  distinct(userid) %&gt;% 
  count() %&gt;% 
  arrange(desc(n)) %&gt;% 
  knitr::kable(&quot;html&quot;)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
account_language
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
2214
</td>
</tr>
<tr>
<td style="text-align:left;">
ru
</td>
<td style="text-align:right;">
982
</td>
</tr>
<tr>
<td style="text-align:left;">
es
</td>
<td style="text-align:right;">
194
</td>
</tr>
<tr>
<td style="text-align:left;">
de
</td>
<td style="text-align:right;">
107
</td>
</tr>
<tr>
<td style="text-align:left;">
ar
</td>
<td style="text-align:right;">
21
</td>
</tr>
<tr>
<td style="text-align:left;">
fr
</td>
<td style="text-align:right;">
11
</td>
</tr>
<tr>
<td style="text-align:left;">
it
</td>
<td style="text-align:right;">
7
</td>
</tr>
<tr>
<td style="text-align:left;">
en-gb
</td>
<td style="text-align:right;">
6
</td>
</tr>
<tr>
<td style="text-align:left;">
zh-cn
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
uk
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
id
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table>
<p>So there’s 11 account languages. I’m going to focus on languages with n &gt; 100 accounts, and recode the rest as “other_6” (since we can assume “uk” == “en-gb”, that’s one language less).</p>
<pre class="r"><code>other_langs_acc &lt;- data_unique %&gt;% 
  distinct(userid, .keep_all = TRUE) %&gt;% 
  group_by(account_language) %&gt;% 
  count() %&gt;% 
  filter(n &lt; 100) %&gt;% 
  select(account_language)

data_unique &lt;- data_unique %&gt;% 
  mutate(account_language = 
           if_else(account_language %in% other_langs_acc$account_language, &quot;other_6&quot;,
                                  account_language))
n_distinct(data_unique$account_language)</code></pre>
<pre><code>## [1] 5</code></pre>
<p>Great! Now we’re down to 5 account languages.</p>
</div>
<div id="ira-dataset-languages-summary" class="section level2">
<h2><span class="header-section-number">1.4</span> IRA Dataset Languages: Summary</h2>
<p>Let’s see how many different languages we have by now.</p>
<pre class="r"><code>unique(c(data_unique$tweet_language, data_unique$account_language))</code></pre>
<pre><code>##  [1] &quot;ru&quot;       &quot;bg&quot;       &quot;en&quot;       &quot;und&quot;      &quot;other_44&quot; &quot;de&quot;      
##  [7] &quot;uk&quot;       &quot;tl&quot;       &quot;es&quot;       &quot;ar&quot;       &quot;fr&quot;       &quot;in&quot;      
## [13] &quot;sr&quot;       &quot;other_6&quot;</code></pre>
<p>Now let’s create a preliminary overview.</p>
<pre class="r"><code>data_count_by_tweet_lang &lt;- data_unique %&gt;%
  # filter(is_retweet == TRUE) %&gt;% 
  group_by(tweet_language) %&gt;%
  distinct(tweetid) %&gt;% 
  count() %&gt;%
  rename(Tweets = n)

data_count_by_account_lang &lt;- data_unique %&gt;%
  # filter(is_retweet == TRUE) %&gt;% 
  group_by(account_language) %&gt;%
  distinct(userid) %&gt;% 
  count() %&gt;%
  rename(Accounts = n)

lang_stats &lt;- full_join(data_count_by_tweet_lang, data_count_by_account_lang,
  by = c(&quot;tweet_language&quot; = &quot;account_language&quot;)) %&gt;%
  rename(Language = tweet_language) %&gt;%
  mutate(
    T.Share = round(Tweets / sum(.$Tweets, na.rm = TRUE) * 100, 2),
    A.Share = round(Accounts / sum(.$Accounts, na.rm = TRUE) * 100, 2)
  ) %&gt;%
  select(Language, Tweets, T.Share, Accounts, A.Share) %&gt;%
  arrange(desc(Accounts))</code></pre>
<pre class="r"><code>lang_stats %&gt;%
  knitr::kable(&quot;html&quot;,
    format.args = list(
      big.mark = &quot;.&quot;,
      decimal.mark = &quot;,&quot;),
    caption = &quot;#TwitterDump 2018 – Russian InfoOP Dataset: Languages (unique Tweets)&quot;
  )</code></pre>
<table>
<caption>
<span id="tab:unnamed-chunk-18">Table 1.1: </span>#TwitterDump 2018 – Russian InfoOP Dataset: Languages (unique Tweets)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Language
</th>
<th style="text-align:right;">
Tweets
</th>
<th style="text-align:right;">
T.Share
</th>
<th style="text-align:right;">
Accounts
</th>
<th style="text-align:right;">
A.Share
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
2.178.206
</td>
<td style="text-align:right;">
38,16
</td>
<td style="text-align:right;">
2.214
</td>
<td style="text-align:right;">
62,40
</td>
</tr>
<tr>
<td style="text-align:left;">
ru
</td>
<td style="text-align:right;">
2.839.362
</td>
<td style="text-align:right;">
49,75
</td>
<td style="text-align:right;">
982
</td>
<td style="text-align:right;">
27,68
</td>
</tr>
<tr>
<td style="text-align:left;">
es
</td>
<td style="text-align:right;">
8.402
</td>
<td style="text-align:right;">
0,15
</td>
<td style="text-align:right;">
194
</td>
<td style="text-align:right;">
5,47
</td>
</tr>
<tr>
<td style="text-align:left;">
de
</td>
<td style="text-align:right;">
86.258
</td>
<td style="text-align:right;">
1,51
</td>
<td style="text-align:right;">
107
</td>
<td style="text-align:right;">
3,02
</td>
</tr>
<tr>
<td style="text-align:left;">
other_6
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
51
</td>
<td style="text-align:right;">
1,44
</td>
</tr>
<tr>
<td style="text-align:left;">
ar
</td>
<td style="text-align:right;">
35.811
</td>
<td style="text-align:right;">
0,63
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
bg
</td>
<td style="text-align:right;">
36.575
</td>
<td style="text-align:right;">
0,64
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
fr
</td>
<td style="text-align:right;">
7.501
</td>
<td style="text-align:right;">
0,13
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
in
</td>
<td style="text-align:right;">
7.543
</td>
<td style="text-align:right;">
0,13
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
other_44
</td>
<td style="text-align:right;">
42.795
</td>
<td style="text-align:right;">
0,75
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
sr
</td>
<td style="text-align:right;">
5.604
</td>
<td style="text-align:right;">
0,10
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
tl
</td>
<td style="text-align:right;">
5.176
</td>
<td style="text-align:right;">
0,09
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
uk
</td>
<td style="text-align:right;">
49.887
</td>
<td style="text-align:right;">
0,87
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
und
</td>
<td style="text-align:right;">
404.557
</td>
<td style="text-align:right;">
7,09
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table>
<blockquote>
<p>That’s already interesting, but let’s not jump to conclusion about who tweeted in what language, yet… This summary alone does enable us to claim that, for instance, Russian accounts where responsible for all the Russian Tweets, and so on.</p>
</blockquote>
<blockquote>
<p>What’s really striking is that 50% of the Tweets from this 9M Tweets IRA dataset are in Russian (or at least labelled as such), which does not quite fit the dominant narrative of a solely US-centric information operation. These numbers show that Russia’s activities were concered with Russian-speaking people as much as with an English-speaking audience (among German and Spanish).</p>
</blockquote>
<p><strong>Check for any remaining language NA’s</strong></p>
<pre class="r"><code>data_unique %&gt;% filter(is.na(tweet_language) | is.na(account_language)) %&gt;% 
  count()</code></pre>
<pre><code>## # A tibble: 1 x 1
##       n
##   &lt;int&gt;
## 1     0</code></pre>
<p>That’s great news, so far!</p>
<p><strong>(Optional: recode if(tweet_lang == NA &amp;/| user_lang == NA))</strong></p>
<p>Since we’ve reduced our dataset and already recoded the <code>NA</code>s, this step is not necessary anymore (before that, I worked without <code>is_retweet == FALSE</code> and things looked a bit different). However, I’m just leaving the syntax here, since it might be useful to others (and to myself).</p>
<pre class="r"><code>data_recoded &lt;- data_unique %&gt;%
  mutate(tweet_language = if_else(is.na(tweet_language) &amp; is.na(account_language),
                                  &quot;und&quot;,
                            if_else(is.na(tweet_language) &amp; !is.na(account_language),
                                    account_language,
                          tweet_language)
                          )
         ) %&gt;% 
  mutate(account_language = if_else(is.na(tweet_language) &amp; is.na(account_language),
                                  &quot;und&quot;,
                              if_else(is.na(account_language) &amp; !is.na(tweet_language),
                                      tweet_language,
                            account_language)
                            )
         )</code></pre>
</div>
</div>
<div id="who-tweeted-in-what-language" class="section level1">
<h1><span class="header-section-number">2</span> Who tweeted in what language?</h1>
<p>Now it’s about time to look into which account language groups tweeted in what languages.</p>
<div id="create-language-specific-subsets" class="section level2">
<h2><span class="header-section-number">2.1</span> Create Language-specific Subsets</h2>
<blockquote>
<p>This is also a good moment to create language-specific or other intereting subsets from our refined dataset.</p>
</blockquote>
<p><strong>German subset</strong></p>
<pre class="r"><code>german_subset &lt;- data_unique %&gt;% filter(tweet_language == &quot;de&quot; | account_language == &quot;de&quot;)</code></pre>
<p>The German subset has 98064 Tweets by 782 users.</p>
<p><strong>Undefined Subset</strong></p>
<pre class="r"><code>undefined_subset &lt;- data_unique %&gt;% 
  filter(tweet_language == &quot;und&quot; | account_language == &quot;und&quot; | 
           is.na(tweet_language) | is.na(account_language))</code></pre>
<p>The undefined (“und” &amp; “NA”) subset has 404557 Tweets by 2867 users.</p>
</div>
<div id="summary-plots-languages-general-activity" class="section level2">
<h2><span class="header-section-number">2.2</span> Summary Plots: Languages &amp; General Activity</h2>
<pre class="r"><code>data_unique %&gt;%
  group_by(tweet_language) %&gt;%
  summarise(n = n()) %&gt;%
  mutate(
    share = n / sum(n),
    tweet_language = case_when(
      tweet_language == &quot;&quot; ~ &quot;unspec.&quot;,
      tweet_language == &quot;und&quot; ~ &quot;undef.&quot;,
      TRUE ~ tweet_language
    )
  ) %&gt;%
  arrange(desc(n)) %&gt;%
  ggplot(aes(area = share)) +
  treemapify::geom_treemap(aes(fill = n), alpha = 0.8) +
  treemapify::geom_treemap_text(
    aes(label = paste0(tweet_language, &quot;\n(&quot;, round(share * 100, 1), &quot;%)&quot;))
  ) +
  scale_fill_viridis_c(direction = -1, option = &quot;D&quot;) +
  labs(
    title = &quot;#TwitterDump 2018 – Russian InfoOP Dataset: Shares of Languages (Tweets)&quot;,
    subtitle = str_c(&quot;Total of &quot;, 
      n_distinct(data_unique$tweetid), &quot; unique Tweets (no RTs) from &quot;,
      n_distinct(data_unique$userid), &quot; unique Users&quot;
    ),
    caption = str_c(&quot;@fubits&quot;)
  ) +
  guides(fill = FALSE)</code></pre>
<p><img src="/post/2018-10-26-election-hacking-exploring-2-million-tweets-from-the-russian-internet-research-agency-dataset-pt-1_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<pre class="r"><code>data_unique %&gt;%
  group_by(account_language) %&gt;%
  summarise(n = n()) %&gt;%
  mutate(
    share = n / sum(n),
    account_language = case_when(
      account_language == &quot;&quot; ~ &quot;unspec.&quot;,
      account_language == &quot;und&quot; ~ &quot;undef.&quot;,
      TRUE ~ account_language
    )
  ) %&gt;%
  arrange(desc(n)) %&gt;%
  ggplot(aes(area = share)) +
  treemapify::geom_treemap(aes(fill = n), alpha = 0.8) +
  treemapify::geom_treemap_text(
    aes(label = paste0(account_language, &quot;\n(&quot;, round(share * 100, 1), &quot;%)&quot;))
  ) +
  scale_fill_viridis_c(direction = -1, option = &quot;D&quot;) +
  labs(
    title = &quot;#TwitterDump 2018 – Russian InfoOP Dataset: Shares of Languages (Accounts)&quot;,
    subtitle = str_c(&quot;Total of &quot;, 
      n_distinct(data_unique$tweetid), &quot; unique Tweets (no RTs) from &quot;,
      n_distinct(data_unique$userid), &quot; unique Users&quot;
    ),
    caption = str_c(&quot;@fubits&quot;)
  ) +
  guides(fill = FALSE)</code></pre>
<p><img src="/post/2018-10-26-election-hacking-exploring-2-million-tweets-from-the-russian-internet-research-agency-dataset-pt-1_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<div id="consolidating-tweet-languages-per-account" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Consolidating Tweet Languages per Account</h3>
<pre class="r"><code>data_counts &lt;- data_unique %&gt;%
  group_by(userid) %&gt;%
  mutate(Account_Lang = account_language) %&gt;% 
  summarise(
    Created = unique(account_creation_date),
    Account_Lang = unique(Account_Lang),
    Tweets = n(),
    RT = sum(retweet_count),
    Follower = unique(follower_count),
    Following = unique(following_count),
    Influence = (((Follower + 1) / (Following + 1)) + (Follower + 1)),
    Tweet_Langs = list(tweet_language),
    Tweet_Langs_Counts = list(unlist(Tweet_Langs) %&gt;% fct_count())
  ) %&gt;%
  arrange(desc(Tweets))</code></pre>
<p>Now the <code>$Tweet_Langs</code> var contains a list of all Tweet Languages from every single Tweet posted by an Account. Compare the number of <code>$Tweets</code> with the length of the vector (in the list) further below.</p>
<p>For <code>$Tweet_Langs_Counts</code>, we have utilized the quite elegant <code>forcats::fct_count()</code> which gives us a <code>list</code> of the aggregated language counts.</p>
<p>So the first User in our dataset - who has tweeted a total of 95210 times - has been busy in 6 languages. Impressive language skills :)</p>
<pre class="r"><code>data_counts[1,]$Tweet_Langs_Counts[[1]] %&gt;% knitr::kable(&quot;html&quot;)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
f
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
bg
</td>
<td style="text-align:right;">
536
</td>
</tr>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
ru
</td>
<td style="text-align:right;">
93478
</td>
</tr>
<tr>
<td style="text-align:left;">
sr
</td>
<td style="text-align:right;">
26
</td>
</tr>
<tr>
<td style="text-align:left;">
uk
</td>
<td style="text-align:right;">
1093
</td>
</tr>
<tr>
<td style="text-align:left;">
und
</td>
<td style="text-align:right;">
75
</td>
</tr>
</tbody>
</table>
<p>And this is what this tibble looks like (without <code>$userid</code> and <code>$Tweet_Langs</code> for better Website readability):</p>
<pre class="r"><code>data_counts %&gt;%  
  select(-userid, -Tweet_Langs) %&gt;% 
  head(10) %&gt;% knitr::kable(&quot;html&quot;, digits = 0)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
Created
</th>
<th style="text-align:left;">
Account_Lang
</th>
<th style="text-align:right;">
Tweets
</th>
<th style="text-align:right;">
RT
</th>
<th style="text-align:right;">
Follower
</th>
<th style="text-align:right;">
Following
</th>
<th style="text-align:right;">
Influence
</th>
<th style="text-align:left;">
Tweet_Langs_Counts
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
16237
</td>
<td style="text-align:left;">
ru
</td>
<td style="text-align:right;">
95210
</td>
<td style="text-align:right;">
188332
</td>
<td style="text-align:right;">
15753
</td>
<td style="text-align:right;">
6862
</td>
<td style="text-align:right;">
15756
</td>
<td style="text-align:left;">
list(f = 1:6, n = c(536, 2, 93478, 26, 1093, 75))
</td>
</tr>
<tr>
<td style="text-align:left;">
14553
</td>
<td style="text-align:left;">
ru
</td>
<td style="text-align:right;">
68784
</td>
<td style="text-align:right;">
11700
</td>
<td style="text-align:right;">
1543
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
1588
</td>
<td style="text-align:left;">
list(f = 1:13, n = c(3, 488, 14, 290, 12, 10, 1, 153, 26633, 90, 9, 686, 40395))
</td>
</tr>
<tr>
<td style="text-align:left;">
16625
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
64495
</td>
<td style="text-align:right;">
1898
</td>
<td style="text-align:right;">
791
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1056
</td>
<td style="text-align:left;">
list(f = 1:11, n = c(17, 1105, 44410, 766, 753, 2561, 13267, 1, 1474, 6, 135))
</td>
</tr>
<tr>
<td style="text-align:left;">
16309
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
59397
</td>
<td style="text-align:right;">
44258
</td>
<td style="text-align:right;">
66980
</td>
<td style="text-align:right;">
10500
</td>
<td style="text-align:right;">
66987
</td>
<td style="text-align:left;">
list(f = 1:8, n = c(64, 58607, 94, 113, 44, 339, 42, 94))
</td>
</tr>
<tr>
<td style="text-align:left;">
16204
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
53781
</td>
<td style="text-align:right;">
29179
</td>
<td style="text-align:right;">
23595
</td>
<td style="text-align:right;">
13665
</td>
<td style="text-align:right;">
23598
</td>
<td style="text-align:left;">
list(f = 1:8, n = c(75, 53067, 90, 135, 28, 308, 9, 69))
</td>
</tr>
<tr>
<td style="text-align:left;">
16227
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
52838
</td>
<td style="text-align:right;">
19670
</td>
<td style="text-align:right;">
29357
</td>
<td style="text-align:right;">
6720
</td>
<td style="text-align:right;">
29362
</td>
<td style="text-align:left;">
list(f = 1:8, n = c(129, 51643, 148, 147, 68, 463, 92, 148))
</td>
</tr>
<tr>
<td style="text-align:left;">
17093
</td>
<td style="text-align:left;">
ru
</td>
<td style="text-align:right;">
50224
</td>
<td style="text-align:right;">
1526
</td>
<td style="text-align:right;">
423
</td>
<td style="text-align:right;">
187
</td>
<td style="text-align:right;">
426
</td>
<td style="text-align:left;">
list(f = 1:7, n = c(247, 1, 2, 49436, 8, 442, 88))
</td>
</tr>
<tr>
<td style="text-align:left;">
16431
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
46738
</td>
<td style="text-align:right;">
3619
</td>
<td style="text-align:right;">
13358
</td>
<td style="text-align:right;">
13851
</td>
<td style="text-align:right;">
13360
</td>
<td style="text-align:left;">
list(f = 1:8, n = c(46, 45943, 149, 115, 48, 293, 43, 101))
</td>
</tr>
<tr>
<td style="text-align:left;">
16195
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
46572
</td>
<td style="text-align:right;">
25119
</td>
<td style="text-align:right;">
35988
</td>
<td style="text-align:right;">
11010
</td>
<td style="text-align:right;">
35992
</td>
<td style="text-align:left;">
list(f = 1:8, n = c(72, 45890, 56, 163, 58, 264, 34, 35))
</td>
</tr>
<tr>
<td style="text-align:left;">
16626
</td>
<td style="text-align:left;">
ru
</td>
<td style="text-align:right;">
46440
</td>
<td style="text-align:right;">
24685
</td>
<td style="text-align:right;">
13913
</td>
<td style="text-align:right;">
1650
</td>
<td style="text-align:right;">
13922
</td>
<td style="text-align:left;">
list(f = 1:7, n = c(344, 1, 4, 45398, 19, 560, 114))
</td>
</tr>
</tbody>
</table>
<p>I’ll get back to this in a minute. Let’s now visualize the general characteristics of all accounts in the IRA dataset.</p>
</div>
<div id="general-activity-plots" class="section level3">
<h3><span class="header-section-number">2.2.2</span> General Activity Plots</h3>
<pre class="r"><code>ggplot(data_counts, aes(x = Follower, y = Following)) +
  geom_point(aes(size = Tweets, color = userid, alpha = Influence)) +
  scale_color_viridis_d(direction = -1) +
  scale_alpha_continuous(range = c(0.3,1),
                         breaks = scales::pretty_breaks(5)) +
  scale_size(range = c(1,5), labels = scales::number_format(big.mark = &quot;.&quot;,
                                                    decimal.mark = &quot;,&quot;)) +
  scale_x_continuous(breaks = scales::pretty_breaks(6),
                     labels = scales::number_format(big.mark = &quot;.&quot;,
                                                    decimal.mark = &quot;,&quot;)) +
  scale_y_continuous(breaks = scales::pretty_breaks(6),
                     labels = scales::number_format(big.mark = &quot;.&quot;,
                                                    decimal.mark = &quot;,&quot;)) +
  coord_fixed() +
  theme_minimal() +
  labs(
    title = &quot;#TwitterDump 2018 – Russian InfoOP Dataset: Account Stats&quot;,
    subtitle = str_c(&quot;Total of &quot;, 
      n_distinct(data_unique$tweetid), &quot; unique Tweets (no RTs) from &quot;,
      n_distinct(data_unique$userid), &quot; unique Users&quot;
    ),
    caption = str_c(&quot;@fubits&quot;),
    #x = &quot;&quot;,
    # y = &quot;&quot;,
    size = &quot;# of Tweets&quot;,
    alpha = &quot;Alpha: # Retweets&quot;
  ) +
    guides(color = FALSE, alpha = FALSE)</code></pre>
<p><img src="/post/2018-10-26-election-hacking-exploring-2-million-tweets-from-the-russian-internet-research-agency-dataset-pt-1_files/figure-html/unnamed-chunk-28-1.png" width="960" /></p>
<p>From what we can see here, we have quite an amount of “influencers” - accounts with lots of followers and low rates of following others.</p>
<p>What if we look at the account languages?</p>
<pre class="r"><code>ggplot(data_counts, aes(x = Follower, y = Following)) +
  geom_point(aes(size = Tweets, color = fct_infreq(Account_Lang), alpha = Influence)) +
  scale_color_viridis_d(option = &quot;B&quot;, direction = 1) +
  scale_alpha_continuous(range = c(0.3,1),
                         labels = scales::number_format(big.mark = &quot;.&quot;,
                                                    decimal.mark = &quot;,&quot;)) +
  scale_size(range = c(1,5), labels = scales::number_format(big.mark = &quot;.&quot;,
                                                    decimal.mark = &quot;,&quot;)) +
  scale_x_continuous(breaks = scales::pretty_breaks(6),
                     labels = scales::number_format(big.mark = &quot;.&quot;,
                                                    decimal.mark = &quot;,&quot;)) +
  scale_y_continuous(breaks = scales::pretty_breaks(6),
                     labels = scales::number_format(big.mark = &quot;.&quot;,
                                                    decimal.mark = &quot;,&quot;)) +
  coord_fixed() +
  theme_minimal() +
  labs(
    title = &quot;#TwitterDump 2018 – Russian InfoOP Dataset: Activity by Account Language&quot;,
    subtitle = str_c(&quot;Total of &quot;, 
      n_distinct(data_unique$tweetid), &quot; unique Tweets (no RTs) from &quot;,
      n_distinct(data_unique$userid), &quot; unique Users&quot;
    ),
    caption = str_c(&quot;@fubits&quot;),
    #x = &quot;&quot;,
    # y = &quot;&quot;,
    size = &quot;# of Tweets&quot;,
    color = &quot;Account Language&quot;
  ) +
    guides(alpha = FALSE,
           colour = guide_legend(override.aes = list(size = 5, stroke = 1.5))
           )</code></pre>
<p><img src="/post/2018-10-26-election-hacking-exploring-2-million-tweets-from-the-russian-internet-research-agency-dataset-pt-1_files/figure-html/unnamed-chunk-29-1.png" width="960" /></p>
<p>And now let’s just look at when the most influential accounts were created.</p>
<pre class="r"><code>influencers &lt;- data_counts %&gt;% 
  arrange(desc(Influence)) %&gt;% 
  top_n(15, Influence)

data_counts %&gt;% 
  arrange(desc(Influence)) %&gt;% 
  ggplot(data = ., aes(x = Follower, y = Following)) +
    geom_point(aes(size = Tweets, color = fct_infreq(Account_Lang), alpha = Influence)) +
    ggrepel::geom_label_repel(data = influencers,
                            aes(label = lubridate::year(Created),
                                fill = Account_Lang),
                            alpha = 0.7) +
    scale_color_viridis_d(option = &quot;B&quot;, direction = 1) +
    scale_alpha_continuous(range = c(0.3,1),
                           labels = scales::number_format(big.mark = &quot;.&quot;,
                                                      decimal.mark = &quot;,&quot;)) +
    scale_size(range = c(1,5), labels = scales::number_format(big.mark = &quot;.&quot;,
                                                      decimal.mark = &quot;,&quot;)) +
    scale_x_continuous(breaks = scales::pretty_breaks(6),
                       labels = scales::number_format(big.mark = &quot;.&quot;,
                                                      decimal.mark = &quot;,&quot;)) +
    scale_y_continuous(breaks = scales::pretty_breaks(6),
                       labels = scales::number_format(big.mark = &quot;.&quot;,
                                                      decimal.mark = &quot;,&quot;)) +
    coord_fixed() +
    theme_minimal() +
    labs(
      title = &quot;#TwitterDump 2018 – Russian InfoOP Dataset: Top 15 (Influence) - Account Creation Date&quot;,
      subtitle = str_c(&quot;Total of &quot;, 
        n_distinct(data_unique$tweetid), &quot; unique Tweets (no RTs) from &quot;,
        n_distinct(data_unique$userid), &quot; unique Users&quot;
      ),
      caption = str_c(&quot;@fubits&quot;),
      #x = &quot;&quot;,
      # y = &quot;&quot;,
      size = &quot;# of Tweets&quot;,
      color = &quot;Account Language&quot;
    ) +
      guides(alpha = FALSE,
             colour = FALSE)</code></pre>
<p><img src="/post/2018-10-26-election-hacking-exploring-2-million-tweets-from-the-russian-internet-research-agency-dataset-pt-1_files/figure-html/unnamed-chunk-30-1.png" width="960" /></p>
<p>Interesting, one of the most influential accounts is neither Russian nor English-speaking!</p>
<pre class="r"><code>data_counts %&gt;% 
  arrange(desc(Influence)) %&gt;% 
  select(userid, Account_Lang, Follower, Following) %&gt;% 
  head(15) %&gt;% knitr::kable(&quot;html&quot;)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
userid
</th>
<th style="text-align:left;">
Account_Lang
</th>
<th style="text-align:right;">
Follower
</th>
<th style="text-align:right;">
Following
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
2527472164
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
257638
</td>
<td style="text-align:right;">
544
</td>
</tr>
<tr>
<td style="text-align:left;">
508761973
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
149672
</td>
<td style="text-align:right;">
1024
</td>
</tr>
<tr>
<td style="text-align:left;">
4224729994
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
147767
</td>
<td style="text-align:right;">
74664
</td>
</tr>
<tr>
<td style="text-align:left;">
449689677
</td>
<td style="text-align:left;">
ru
</td>
<td style="text-align:right;">
123989
</td>
<td style="text-align:right;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
2808833544
</td>
<td style="text-align:left;">
ru
</td>
<td style="text-align:right;">
134805
</td>
<td style="text-align:right;">
2796
</td>
</tr>
<tr>
<td style="text-align:left;">
2648734430
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
106462
</td>
<td style="text-align:right;">
386
</td>
</tr>
<tr>
<td style="text-align:left;">
890237781737435138
</td>
<td style="text-align:left;">
ru
</td>
<td style="text-align:right;">
51964
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
3676820373
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
85293
</td>
<td style="text-align:right;">
316
</td>
</tr>
<tr>
<td style="text-align:left;">
3729867851
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
84167
</td>
<td style="text-align:right;">
143
</td>
</tr>
<tr>
<td style="text-align:left;">
2665564544
</td>
<td style="text-align:left;">
ru
</td>
<td style="text-align:right;">
84642
</td>
<td style="text-align:right;">
2575
</td>
</tr>
<tr>
<td style="text-align:left;">
2882331822
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
79152
</td>
<td style="text-align:right;">
22607
</td>
</tr>
<tr>
<td style="text-align:left;">
4272870988
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
72121
</td>
<td style="text-align:right;">
42080
</td>
</tr>
<tr>
<td style="text-align:left;">
2752677905
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
66980
</td>
<td style="text-align:right;">
10500
</td>
</tr>
<tr>
<td style="text-align:left;">
2518710111
</td>
<td style="text-align:left;">
other_6
</td>
<td style="text-align:right;">
60869
</td>
<td style="text-align:right;">
1246
</td>
</tr>
<tr>
<td style="text-align:left;">
2573726278
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
59724
</td>
<td style="text-align:right;">
556
</td>
</tr>
</tbody>
</table>
<blockquote>
<p>2518710111 is not hashed :) Let’s find out who this is!</p>
</blockquote>
<pre class="r"><code>data_raw %&gt;% filter(userid == 2518710111) %&gt;% select(userid, user_display_name, user_screen_name, account_language) %&gt;% head(1) %&gt;% knitr::kable(&quot;html&quot;)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
userid
</th>
<th style="text-align:left;">
user_display_name
</th>
<th style="text-align:left;">
user_screen_name
</th>
<th style="text-align:left;">
account_language
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
2518710111
</td>
<td style="text-align:left;">
Вестник Новосибирска
</td>
<td style="text-align:left;">
NovostiNsk
</td>
<td style="text-align:left;">
en-gb
</td>
</tr>
</tbody>
</table>
<blockquote>
<p>“Вестник Новосибирска” - Newspaper of Novosibirsk - doesn’t sound too British :) the account has been suspended by Twitter, btw.</p>
</blockquote>
<p>What about accounts with the most Tweets?</p>
<pre class="r"><code>data_counts %&gt;% 
  ggplot(data = ., aes(x = Follower, y = Following)) +
    geom_point(aes(size = Tweets, color = fct_infreq(Account_Lang), alpha = RT)) +
    ggrepel::geom_label_repel(data = data_counts[1:15,],
                            aes(label = lubridate::year(Created),
                                fill = Account_Lang),
                            alpha = 0.7) +
    scale_color_viridis_d(option = &quot;B&quot;, direction = 1) +
    scale_alpha_continuous(range = c(0.3,1),
                           labels = scales::number_format(big.mark = &quot;.&quot;,
                                                      decimal.mark = &quot;,&quot;)) +
    scale_size(range = c(1,5), labels = scales::number_format(big.mark = &quot;.&quot;,
                                                      decimal.mark = &quot;,&quot;)) +
    scale_x_continuous(breaks = scales::pretty_breaks(6),
                       labels = scales::number_format(big.mark = &quot;.&quot;,
                                                      decimal.mark = &quot;,&quot;)) +
    scale_y_continuous(breaks = scales::pretty_breaks(6),
                       labels = scales::number_format(big.mark = &quot;.&quot;,
                                                      decimal.mark = &quot;,&quot;)) +
    coord_fixed() +
    theme_minimal() +
    labs(
      title = &quot;#TwitterDump 2018 – Russian InfoOP Dataset: Top 15 (# Tweets) - Account Creation Date&quot;,
      subtitle = str_c(&quot;Total of &quot;, 
        n_distinct(data_unique$tweetid), &quot; unique Tweets (no RTs) from &quot;,
        n_distinct(data_unique$userid), &quot; unique Users&quot;
      ),
      caption = str_c(&quot;@fubits&quot;),
      #x = &quot;&quot;,
      # y = &quot;&quot;,
      size = &quot;# of Tweets&quot;,
      color = &quot;Account Language&quot;
    ) +
      guides(alpha = FALSE,
             colour = FALSE)</code></pre>
<p><img src="/post/2018-10-26-election-hacking-exploring-2-million-tweets-from-the-russian-internet-research-agency-dataset-pt-1_files/figure-html/unnamed-chunk-33-1.png" width="960" /></p>
<p>We can see from both plots that the most influential or active accounts were created in 2014 or later, and that the relation between Russian- and English-labelled accounts is rather balanced in terms of max. Tweet numbers. However, English-speaking accounts are more dominant in terms of numeric dominance (Following/Followers).</p>
</div>
</div>
<div id="languages-accounts-vs-tweets" class="section level2">
<h2><span class="header-section-number">2.3</span> Languages: Accounts vs Tweets</h2>
<p>Now it’s time to have look at the <strong>account language to tweet languages</strong> relations.</p>
<p>This is what the Top 20 (of 57) language combinations look like:</p>
<pre class="r"><code>data_unique %&gt;% 
  group_by(account_language, tweet_language) %&gt;% 
  count() %&gt;% 
  arrange(desc(n)) %&gt;% 
  head(20) %&gt;% 
  knitr::kable(&quot;html&quot;, caption = &quot;Top 20 Language Combinations from the IRA Dataset&quot;)</code></pre>
<table>
<caption>
<span id="tab:unnamed-chunk-34">Table 2.1: </span>Top 20 Language Combinations from the IRA Dataset
</caption>
<thead>
<tr>
<th style="text-align:left;">
account_language
</th>
<th style="text-align:left;">
tweet_language
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
ru
</td>
<td style="text-align:left;">
ru
</td>
<td style="text-align:right;">
1985869
</td>
</tr>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
1842222
</td>
</tr>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:left;">
ru
</td>
<td style="text-align:right;">
836074
</td>
</tr>
<tr>
<td style="text-align:left;">
ru
</td>
<td style="text-align:left;">
und
</td>
<td style="text-align:right;">
310192
</td>
</tr>
<tr>
<td style="text-align:left;">
es
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
275732
</td>
</tr>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:left;">
und
</td>
<td style="text-align:right;">
80810
</td>
</tr>
<tr>
<td style="text-align:left;">
de
</td>
<td style="text-align:left;">
de
</td>
<td style="text-align:right;">
78301
</td>
</tr>
<tr>
<td style="text-align:left;">
other_6
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
51105
</td>
</tr>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:left;">
other_44
</td>
<td style="text-align:right;">
35542
</td>
</tr>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:left;">
ar
</td>
<td style="text-align:right;">
33013
</td>
</tr>
<tr>
<td style="text-align:left;">
ru
</td>
<td style="text-align:left;">
uk
</td>
<td style="text-align:right;">
28038
</td>
</tr>
<tr>
<td style="text-align:left;">
ru
</td>
<td style="text-align:left;">
bg
</td>
<td style="text-align:right;">
21923
</td>
</tr>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:left;">
uk
</td>
<td style="text-align:right;">
21520
</td>
</tr>
<tr>
<td style="text-align:left;">
other_6
</td>
<td style="text-align:left;">
ru
</td>
<td style="text-align:right;">
17679
</td>
</tr>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:left;">
bg
</td>
<td style="text-align:right;">
14539
</td>
</tr>
<tr>
<td style="text-align:left;">
de
</td>
<td style="text-align:left;">
und
</td>
<td style="text-align:right;">
10387
</td>
</tr>
<tr>
<td style="text-align:left;">
ru
</td>
<td style="text-align:left;">
en
</td>
<td style="text-align:right;">
8500
</td>
</tr>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:left;">
es
</td>
<td style="text-align:right;">
7259
</td>
</tr>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:left;">
de
</td>
<td style="text-align:right;">
6637
</td>
</tr>
<tr>
<td style="text-align:left;">
en
</td>
<td style="text-align:left;">
in
</td>
<td style="text-align:right;">
6407
</td>
</tr>
</tbody>
</table>
<p>Ok, so we probably could have expected that Russian and English speaking accounts would mostly tweet in their respective languages. But who would have suspected that 185.803 Russian language tweets were posted by English-speaking accounts? Right :)</p>
<p>Now let’s visualize all the 57 <strong>Account Language -&gt; Tweet Language</strong> combinations. For an easier understanding of these plots, just keep in mind that Tweets are posted by accounts, so the Tweet language (bottom) is our dependent variable here.</p>
<pre class="r"><code>data_unique %&gt;% 
  group_by(account_language, tweet_language) %&gt;% 
  count() %&gt;% 
  arrange(desc(n)) %&gt;% 
    ggplot() +
    geom_tile(aes(x = tweet_language,
                  y = account_language,
                  fill = n)) +
    scale_fill_viridis_c(option = &quot;B&quot;, direction = -1,
                         breaks = scales::pretty_breaks(4),
                         labels = scales::number_format(big.mark = &quot;.&quot;,
                                                        decimal.mark = &quot;,&quot;)) + 
    coord_fixed() +
    theme_minimal() +
    labs(
      title = &quot;#TwitterDump 2018 – Russian InfoOP Dataset: Language Matrix&quot;,
      subtitle = str_c(
        &quot;Subset of &quot;, n_distinct(data_unique$tweetid),
        &quot; unique Tweets (no RTs) from &quot;,
        n_distinct(data_unique$userid), &quot; unique Users&quot;
      ),
      caption = str_c(&quot;@fubits&quot;),
      fill = &quot;Language Combo:\nTotals&quot;,
      x = &quot;Tweet Language&quot;,
      y = &quot;Account Language&quot;
    )</code></pre>
<p><img src="/post/2018-10-26-election-hacking-exploring-2-million-tweets-from-the-russian-internet-research-agency-dataset-pt-1_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<pre class="r"><code>data_unique %&gt;% 
  group_by(account_language, tweet_language) %&gt;% 
  count() %&gt;% 
  arrange(desc(n)) %&gt;% 
    ggplot() +
    geom_tile(aes(x = tweet_language, 
                  y = account_language,
                  fill = n/sum(n))) +
    scale_fill_viridis_c(option = &quot;B&quot;, direction = -1,
                         breaks = scales::pretty_breaks(6),
                         labels = scales::percent_format(accuracy = 1)) + 
    coord_fixed() +
    theme_minimal() +
  # theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
    labs(
      title = &quot;#TwitterDump 2018 – Russian InfoOP Dataset: Language Matrix&quot;,
      subtitle = str_c(
        &quot;Subset of &quot;, n_distinct(data_unique$tweetid), 
        &quot; unique Tweets (no RTs) from &quot;,
        n_distinct(data_unique$userid), &quot; unique Users&quot;
      ),
      caption = str_c(&quot;@fubits&quot;),
      fill = &quot;Language Combo:\nShare of Total&quot;
    )</code></pre>
<p><img src="/post/2018-10-26-election-hacking-exploring-2-million-tweets-from-the-russian-internet-research-agency-dataset-pt-1_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<blockquote>
<p>Alright, that’s enough exploration and heavy data wrangling for today. Stay tuned for Part 2: Content Analysis</p>
</blockquote>
<p>Here’s just a teaser of what is expecting us:</p>
<pre class="r"><code>data_unique %&gt;%
  filter(tweet_language == &quot;ru&quot;) %&gt;% 
  select(tweet_text) %&gt;% 
  head(10) %&gt;%
  knitr::kable(&quot;html&quot;)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
tweet_text
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Серебром отколоколило <a href="http://t.co/Jaa4v4IFpM" class="uri">http://t.co/Jaa4v4IFpM</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
Предлагаю судить их за поддержку нацизма, т.к. они отказались его осуждать!! #STOPNazi
</td>
</tr>
<tr>
<td style="text-align:left;">
Двойная утопия, или Нет у Европы Трампа, кроме Путина <a href="https://t.co/MbxCpuLdDl" class="uri">https://t.co/MbxCpuLdDl</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
Генпрокуратура назвала взносы на капремонт неконституционными <a href="https://t.co/IOiSR4kssB" class="uri">https://t.co/IOiSR4kssB</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
Кировский пасхальный обед один из самых дешевых в стране <a href="https://t.co/11se2vaZJS" class="uri">https://t.co/11se2vaZJS</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
В Кирове на два месяца будет ограничено движение по улице Кольцова <a href="https://t.co/iRT0jWIS9z" class="uri">https://t.co/iRT0jWIS9z</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
Пятница в Кирове: солнечный чай и любимое занятие <a href="https://t.co/jATZrjoAdy" class="uri">https://t.co/jATZrjoAdy</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
ИнстаКиров: топ прокачанных парней в спортзале <a href="http://t.co/q45lGEaHla" class="uri">http://t.co/q45lGEaHla</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
Что обсуждают в Кирове: убийство женщины и концерт “Арии” <a href="https://t.co/MUhZaTSXAA" class="uri">https://t.co/MUhZaTSXAA</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
В музее Циолковского открылась выставка, посвященная нашему земляку Юрию Тухаринову <a href="https://t.co/T3BR53yu7B" class="uri">https://t.co/T3BR53yu7B</a> <a href="https://t.co/WDDkBworPE" class="uri">https://t.co/WDDkBworPE</a>
</td>
</tr>
</tbody>
</table>
<p>Or what about “undefined”</p>
<pre class="r"><code>data_unique %&gt;%
  filter(tweet_language == &quot;und&quot;) %&gt;% 
  select(tweet_text) %&gt;% 
  head(10) %&gt;% 
  knitr::kable(&quot;html&quot;)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
tweet_text
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
#волгоград #сталинград <a href="https://t.co/RCoCV12FP0" class="uri">https://t.co/RCoCV12FP0</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
*** <a href="http://t.co/qpmvojRvYx" class="uri">http://t.co/qpmvojRvYx</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@stratosathens</span> Strat, Every time we are in the state of burning chemical plants! Why is it happened with us?!
</td>
</tr>
<tr>
<td style="text-align:left;">
<a href="http://t.co/RFTj00YJXU" class="uri">http://t.co/RFTj00YJXU</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
<a href="https://t.co/pDSEWw50AH" class="uri">https://t.co/pDSEWw50AH</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
<a href="http://t.co/yYLD9IhvYO" class="uri">http://t.co/yYLD9IhvYO</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@b059c98801ff33056eb46bee9088256f2b6b85dc8d6926579bf42dbf1b2d9c1a</span> Curiosity «завис» на Марсе из-за сбоя в компьютере
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@bee7d3ea2fb7ece347e636f3c21b9340e1e17626bfd7543d1d36b51d00d0a4ce</span> Чехия испытывает дефицит российской нефти
</td>
</tr>
<tr>
<td style="text-align:left;">
Автомобиль Дворковича попал в ДТП
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="citation">@050f6f287ff564463cb290ec9933a045e07d0eea41352e3ed893cd570e97adbb</span> “Доктор Питер”: Петербургские инвесторы могут построить в Белоруссии фармацевтический завод #СПб #spb
</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Btw, have you already discovered the US-Republican-sponsored (sic!) <a href="https://russiatweets.com/" target="_blank">RussiaTweets.com</a> Project?</p>
</blockquote>
</div>
</div>
