---
title: '[R] Joyplots: The (un)joyful Distribution of Grades from German State Exam (Laws)'
author: fubits
date: '2018-03-06'
slug: r-joyplots-the-un-joyful-distribution-of-grades-from-german-state-exam-laws
categories:
  - Rstats
  - DataViz
tags:
  - joyplot
  - ggridges
  - ggplot
lastmod: '2018-05-20T13:52:11+02:00'
keywords: []
description: ''
comment: no
toc: no
autoCollapseToc: no
postMetaInFooter: no
hiddenFromHomePage: no
contentCopyright: no
reward: no
mathjax: no
mathjaxEnableSingleDollar: no
mathjaxEnableAutoNumber: no
hideHeaderAndFooter: no
flowchartDiagrams:
  enable: no
  options: ''
sequenceDiagrams:
  enable: no
  options: ''
---

German **Staatsexamen** (State Exam in Laws) is hard. Let's have a look how hard it is by visualising the distribution of grades from the written exams from the Berlin 2017/IV campaign.

### Import
```{r, message=FALSE}
library(tidyverse)
# Datenquelle: https://www.berlin.de/sen/justiz/juristenausbildung/juristische-pruefungen/artikel.264039.php
noten_raw <- read_csv2("../../data/201801_notenaushang.csv") # nach PDF -> Tabulizer
```

### Skim / Preview
```{r}
skimr::skim(noten_raw)
```

### Long -> Short (Tidy)
```{r echo=TRUE}
noten_raw %>%
  select(-AZ) %>% 
  gather(key = Fach, value = noten_raw[,2:8]) %>% 
  rename(Punkte = `noten_raw[, 2:8]`) -> noten_long
head(noten_long, 1)

```


### Joyplot
```{r, echo=TRUE}
library(ggridges)
library(viridis)
```

#### Beschriftungen
```{r echo=TRUE}
# Beschriftungen
title_a <- c("2. Juristisches Staatsexamen, GJPA Berlin/Brandenburg")
subtitle_a = c("Notenverteilung Kampagne 4/17; n = 263; \"Dur\" = durchschnittl. Examensnote\r\nLinien: blau  = \"bestanden (ausreichend)\", rot  = \"vollbefriedigend\", schwarz  = Median Gesamtnote (5,57")
caption_a = c("@fubits; Daten: GJPA 2018")
```


```{r fig.asp=1, echo=TRUE, message=FALSE}
# Plot
noten_long %>% 
  ggplot() +
  geom_density_ridges(aes(x = Punkte, y = Fach, fill = Fach),
                      rel_min_height = 0.025,
                      scale = 1.75) +
  # Linie: Vollbefriedigend
  geom_vline(xintercept = 10, color = "red", linetype = 4, size = 1) + 
  # Linie: Bestanden
  geom_vline(xintercept = 4, color = "blue", linetype = 4, size = 1) +
  # Linie: Median Gesamtnote
  geom_vline(xintercept = 5.57, color = "black", size = 1) +
  labs(title = title_a, subtitle = subtitle_a, caption = caption_a) +
  scale_x_continuous(breaks = c(0:18), limits = c(0,18)) +
  scale_y_discrete(expand = c(0.01,0.0)) +
  scale_fill_viridis(option = "D", name = "Frequency n",
                     direction = -1, discrete = TRUE) +
  theme(legend.position = "none")
```


### Boxplots für Gesamtergebnis (Dur) und nach Fächern
```{r ECHO=TRUE, fig.asp=1}
noten_long %>% 
ggplot() +
  geom_boxplot(aes(x = Fach, y = Punkte, fill = Fach)) +
  scale_y_continuous(breaks = c(0:18), limits = c(0, 18)) +
  scale_fill_viridis(
    option = "C",
    direction = -1, discrete = TRUE
  ) +
  labs(title = title_a, subtitle = subtitle_a, caption = caption_a) +
  theme(legend.position = "none") +
  # Linien zur Orientierung
  geom_hline(yintercept = 10, color = "red", linetype = 4, size = 1) +
  geom_hline(yintercept = 4, color = "blue", linetype = 4, size = 1) +
  geom_hline(yintercept = 5.57, color = "black", size = 1)
```